/*
@license
dhtmlxScheduler.Net v.3.3.4 

This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Scheduler.plugin(function(e){e.attachEvent("onTimelineCreated",function(t){"tree"==t.render&&(t.y_unit_original=t.y_unit,t.y_unit=e._getArrayToDisplay(t.y_unit_original),e.attachEvent("onOptionsLoadStart",function(){t.y_unit=e._getArrayToDisplay(t.y_unit_original)}),e.form_blocks[t.name]={render:function(e){var t="<div class='dhx_section_timeline' style='overflow: hidden; height: "+e.height+"px'></div>";return t},set_value:function(t,a,n,i){var r=e._getArrayForSelect(e.matrix[i.type].y_unit_original,i.type);

t.innerHTML="";var l=document.createElement("select");t.appendChild(l);var o=t.getElementsByTagName("select")[0];!o._dhx_onchange&&i.onchange&&(o.onchange=i.onchange,o._dhx_onchange=!0);for(var d=0;d<r.length;d++){var _=document.createElement("option");_.value=r[d].key,_.value==n[e.matrix[i.type].y_property]&&(_.selected=!0),_.innerHTML=r[d].label,o.appendChild(_)}},get_value:function(e,t,a){return e.firstChild.value},focus:function(e){}})}),e.attachEvent("onBeforeSectionRender",function(t,a,n){var i={};

if("tree"==t){var r,l,o,d,_,s;a.children?(r=n.folder_dy||n.dy,n.folder_dy&&!n.section_autoheight&&(o="height:"+n.folder_dy+"px;"),l="dhx_row_folder",d="dhx_matrix_scell folder",_="<div class='dhx_scell_expand'>"+(a.open?"-":"+")+"</div>",s=n.folder_events_available?"dhx_data_table folder_events":"dhx_data_table folder"):(r=n.dy,l="dhx_row_item",d="dhx_matrix_scell item"+(e.templates[n.name+"_scaley_class"](a.key,a.label,a)?" "+e.templates[n.name+"_scaley_class"](a.key,a.label,a):""),_="",s="dhx_data_table");

var c="<div class='dhx_scell_level"+a.level+"'>"+_+"<div class='dhx_scell_name'>"+(e.templates[n.name+"_scale_label"](a.key,a.label,a)||a.label)+"</div></div>";i={height:r,style_height:o,tr_className:l,td_className:d,td_content:c,table_className:s}}return i});var t;e.attachEvent("onBeforeEventChanged",function(a,n,i){if(e._isRender("tree"))for(var r=e._get_event_sections?e._get_event_sections(a):[a[e.matrix[e._mode].y_property]],l=0;l<r.length;l++){var o=e.getSection(r[l]);if(o&&"undefined"!=typeof o.children&&!e.matrix[e._mode].folder_events_available)return i||(a[e.matrix[e._mode].y_property]=t),
!1}return!0}),e.attachEvent("onBeforeDrag",function(a,n,i){if(e._isRender("tree")){var r,l=e._locate_cell_timeline(i);if(l&&(r=e.matrix[e._mode].y_unit[l.y].key,"undefined"!=typeof e.matrix[e._mode].y_unit[l.y].children&&!e.matrix[e._mode].folder_events_available))return!1;var o=e.getEvent(a),d=e.matrix[e._mode].y_property;t=o&&o[d]?o[d]:r}return!0}),e._getArrayToDisplay=function(t){var a=[],n=function(t,i){for(var r=i||0,l=0;l<t.length;l++)t[l].level=r,"undefined"!=typeof t[l].children&&"undefined"==typeof t[l].key&&(t[l].key=e.uid()),
a.push(t[l]),t[l].open&&t[l].children&&n(t[l].children,r+1)};return n(t),a},e._getArrayForSelect=function(t,a){var n=[],i=function(t){for(var r=0;r<t.length;r++)e.matrix[a].folder_events_available?n.push(t[r]):"undefined"==typeof t[r].children&&n.push(t[r]),t[r].children&&i(t[r].children,a)};return i(t),n},e._toggleFolderDisplay=function(t,a,n){var i,r=function(e,t,a,n){for(var l=0;l<t.length&&(t[l].key!=e&&!n||!t[l].children||(t[l].open="undefined"!=typeof a?a:!t[l].open,i=!0,n||!i));l++)t[l].children&&r(e,t[l].children,a,n);

},l=e.getSection(t);"undefined"!=typeof a||n||(a=!l.open),e.callEvent("onBeforeFolderToggle",[l,a,n])&&(r(t,e.matrix[e._mode].y_unit_original,a,n),e.matrix[e._mode].y_unit=e._getArrayToDisplay(e.matrix[e._mode].y_unit_original),e.callEvent("onOptionsLoad",[]),e.callEvent("onAfterFolderToggle",[l,a,n]))},e.attachEvent("onCellClick",function(t,a,n,i,r){e._isRender("tree")&&(e.matrix[e._mode].folder_events_available||"undefined"!=typeof e.matrix[e._mode].y_unit[a]&&"undefined"!=typeof e.matrix[e._mode].y_unit[a].children&&e._toggleFolderDisplay(e.matrix[e._mode].y_unit[a].key));

}),e.attachEvent("onYScaleClick",function(t,a,n){e._isRender("tree")&&"undefined"!=typeof a.children&&e._toggleFolderDisplay(a.key)}),e.getSection=function(t){if(e._isRender("tree")){var a,n=function(e,t){for(var i=0;i<t.length;i++)t[i].key==e&&(a=t[i]),t[i].children&&n(e,t[i].children)};return n(t,e.matrix[e._mode].y_unit_original),a||null}},e.deleteSection=function(t){if(e._isRender("tree")){var a=!1,n=function(e,t){for(var i=0;i<t.length&&(t[i].key==e&&(t.splice(i,1),a=!0),!a);i++)t[i].children&&n(e,t[i].children);

};return n(t,e.matrix[e._mode].y_unit_original),e.matrix[e._mode].y_unit=e._getArrayToDisplay(e.matrix[e._mode].y_unit_original),e.callEvent("onOptionsLoad",[]),a}},e.deleteAllSections=function(){e._isRender("tree")&&(e.matrix[e._mode].y_unit_original=[],e.matrix[e._mode].y_unit=e._getArrayToDisplay(e.matrix[e._mode].y_unit_original),e.callEvent("onOptionsLoad",[]))},e.addSection=function(t,a){if(e._isRender("tree")){var n=!1,i=function(e,t,r){if(a)for(var l=0;l<r.length&&(r[l].key==t&&"undefined"!=typeof r[l].children&&(r[l].children.push(e),
n=!0),!n);l++)r[l].children&&i(e,t,r[l].children);else r.push(e),n=!0};return i(t,a,e.matrix[e._mode].y_unit_original),e.matrix[e._mode].y_unit=e._getArrayToDisplay(e.matrix[e._mode].y_unit_original),e.callEvent("onOptionsLoad",[]),n}},e.openAllSections=function(){e._isRender("tree")&&e._toggleFolderDisplay(1,!0,!0)},e.closeAllSections=function(){e._isRender("tree")&&e._toggleFolderDisplay(1,!1,!0)},e.openSection=function(t){e._isRender("tree")&&e._toggleFolderDisplay(t,!0)},e.closeSection=function(t){
e._isRender("tree")&&e._toggleFolderDisplay(t,!1)}});