/*
@license
dhtmlxScheduler.Net v.3.3.4 

This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Scheduler.plugin(function(e){e._temp_matrix_scope=function(){function t(){for(var t=e.get_visible_events(),a=[],n=0;n<this.y_unit.length;n++)a[n]=[];a[i]||(a[i]=[]);for(var n=0;n<t.length;n++){for(var i=this.order[t[n][this.y_property]],r=0;this._trace_x[r+1]&&t[n].start_date>=this._trace_x[r+1];)r++;for(;this._trace_x[r]&&t[n].end_date>this._trace_x[r];)a[i][r]||(a[i][r]=[]),a[i][r].push(t[n]),r++}return a}function a(t,a,n){var i=0,r=n._step,l=n.round_position,o=0,d=a?t.end_date:t.start_date;d.valueOf()>e._max_date.valueOf()&&(d=e._max_date);

var _=d-e._min_date_timeline;if(_>0){var s=e._get_date_index(n,d);e._ignores[s]&&(l=!0);for(var c=0;s>c;c++)i+=e._cols[c];var u=e.date.add(e._min_date_timeline,e.matrix[e._mode].x_step*s,e.matrix[e._mode].x_unit);l?+d>+u&&a&&(o=e._cols[s]):(_=d-u,n.first_hour||n.last_hour?(_-=n._start_correction,0>_&&(_=0),o=Math.round(_/r),o>e._cols[s]&&(o=e._cols[s])):o=Math.round(_/r))}return i+=a?0===_||l?o-14:o-12:o+1}function n(t,a){var n=e._get_date_index(this,t),i=this._trace_x[n];return a&&+t!=+this._trace_x[n]&&(i=this._trace_x[n+1]?this._trace_x[n+1]:e.date.add(this._trace_x[n],this.x_step,this.x_unit)),
new Date(i)}function i(t){if(e._ignores_detected)for(var a,n,i,r,l=0;l<t.length;l++){for(r=t[l],i=!1,a=e._get_date_index(this,r.start_date),n=e._get_date_index(this,r.end_date);n>a;){if(!e._ignores[a]){i=!0;break}a++}i||a!=n||e._ignores[n]||+r.end_date>+this._trace_x[n]&&(i=!0),i||(t.splice(l,1),l--)}}function r(t){var a="";if(t&&"cell"!=this.render){i.call(this,t),t.sort(this.sort||function(e,t){return e.start_date.valueOf()==t.start_date.valueOf()?e.id>t.id?1:-1:e.start_date>t.start_date?1:-1});

for(var r=[],l=t.length,o=0;l>o;o++){var d=t[o];d._inner=!1;var _=this.round_position?n.apply(this,[d.start_date,!1]):d.start_date;for(this.round_position?n.apply(this,[d.end_date,!0]):d.end_date;r.length;){var s=r[r.length-1];if(!(s.end_date.valueOf()<=_.valueOf()))break;r.splice(r.length-1,1)}for(var c=!1,u=0;u<r.length;u++){var p=r[u];if(p.end_date.valueOf()<=_.valueOf()){c=!0,d._sorder=p._sorder,r.splice(u,1),d._inner=!0;break}}if(r.length&&(r[r.length-1]._inner=!0),!c)if(r.length)if(r.length<=r[r.length-1]._sorder){
if(r[r.length-1]._sorder)for(var h=0;h<r.length;h++){for(var v=!1,m=0;m<r.length;m++)if(r[m]._sorder==h){v=!0;break}if(!v){d._sorder=h;break}}else d._sorder=0;d._inner=!0}else{for(var g=r[0]._sorder,b=1;b<r.length;b++)r[b]._sorder>g&&(g=r[b]._sorder);d._sorder=g+1,d._inner=!1}else d._sorder=0;r.push(d),r.length>(r.max_count||0)?(r.max_count=r.length,d._count=r.length):d._count=d._count?d._count:1}for(var y=0;y<t.length;y++)t[y]._count=r.max_count;for(var f=0;l>f;f++)a+=e.render_timeline_event.call(this,t[f],!1);

}return a}function l(a){var n="<table style='table-layout:fixed;' cellspacing='0' cellpadding='0'>",i=[];if(e._load_mode&&e._load(),"cell"==this.render)i=t.call(this);else for(var l=e.get_visible_events(),o=this.order,d=0;d<l.length;d++){var _=l[d],s=_[this.y_property],c=this.order[s];if(this.show_unassigned&&!s){for(var u in o)if(o.hasOwnProperty(u)){c=o[u],i[c]||(i[c]=[]);var p=e._lame_copy({},_);p[this.y_property]=u,i[c].push(p)}}else i[c]||(i[c]=[]),i[c].push(_)}for(var h=0,v=0;v<e._cols.length;v++)h+=e._cols[v];

var m=new Date,g=e._cols.length-e._ignores_detected;m=(e.date.add(m,this.x_step*g,this.x_unit)-m-(this._start_correction+this._end_correction)*g)/h,this._step=m,this._summ=h;var b=e._colsS.heights=[],y=[];this._events_height={},this._section_height={};for(var v=0;v<this.y_unit.length;v++){var f=this._logic(this.render,this.y_unit[v],this);e._merge(f,{height:this.dy}),this.section_autoheight&&(this.y_unit.length*f.height<a.offsetHeight&&(f.height=Math.max(f.height,Math.floor((a.offsetHeight-1)/this.y_unit.length))),
this._section_height[this.y_unit[v].key]=f.height),f.td_className||(f.td_className="dhx_matrix_scell"+(e.templates[this.name+"_scaley_class"](this.y_unit[v].key,this.y_unit[v].label,this.y_unit[v])?" "+e.templates[this.name+"_scaley_class"](this.y_unit[v].key,this.y_unit[v].label,this.y_unit[v]):"")),f.td_content||(f.td_content=e.templates[this.name+"_scale_label"](this.y_unit[v].key,this.y_unit[v].label,this.y_unit[v])),e._merge(f,{tr_className:"",style_height:"height:"+f.height+"px;",style_width:"width:"+(this.dx-1)+"px;",
summ_width:"width:"+h+"px;",table_className:""});var x=r.call(this,i[v]);if(this.fit_events){var k=this._events_height[this.y_unit[v].key]||0;f.height=k>f.height?k:f.height,f.style_height="height:"+f.height+"px;",this._section_height[this.y_unit[v].key]=f.height}if(n+="<tr class='"+f.tr_className+"' style='"+f.style_height+"'><td class='"+f.td_className+"' style='"+f.style_width+" height:"+(f.height-1)+"px;'>"+f.td_content+"</td>","cell"==this.render)for(var d=0;d<e._cols.length;d++)n+=e._ignores[d]?"<td></td>":"<td class='dhx_matrix_cell "+e.templates[this.name+"_cell_class"](i[v][d],this._trace_x[d],this.y_unit[v])+"' style='width:"+(e._cols[d]-1)+"px'><div style='width:"+(e._cols[d]-1)+"px'>"+e.templates[this.name+"_cell_value"](i[v][d],this._trace_x[d],this.y_unit[v])+"</div></td>";
else{n+="<td><div style='"+f.summ_width+" "+f.style_height+" position:relative;' class='dhx_matrix_line'>",n+=x,n+="<table class='"+f.table_className+"' cellpadding='0' cellspacing='0' style='"+f.summ_width+" "+f.style_height+"' >";for(var d=0;d<e._cols.length;d++)n+=e._ignores[d]?"<td></td>":"<td class='dhx_matrix_cell "+e.templates[this.name+"_cell_class"](i[v],this._trace_x[d],this.y_unit[v])+"' style='width:"+(e._cols[d]-1)+"px'><div style='width:"+(e._cols[d]-1)+"px'></div></td>";n+="</table>",
n+="</div></td>"}n+="</tr>",y.push(f)}n+="</table>",this._matrix=i,a.innerHTML=n,e._rendered=[];for(var w=e._obj.getElementsByTagName("DIV"),v=0;v<w.length;v++)w[v].getAttribute("event_id")&&e._rendered.push(w[v]);this._scales={};for(var D=a.firstChild.rows,E=null,v=0,M=y.length;M>v;v++){E=this.y_unit[v],b.push(y[v].height);var S=E.key,N=this._scales[S]=e._isRender("cell")?D[v]:D[v].childNodes[1].getElementsByTagName("div")[0];e.callEvent("onScaleAdd",[N,S])}}function o(t){var a=e._min_date,n=e._max_date;

e._process_ignores(a,this.x_size,this.x_unit,this.x_step,t);for(var i=(this.x_size+(t?e._ignores_detected:0),0),r=0;+n>+a;)if(this._trace_x[r]=new Date(a),a=e.date.add(a,this.x_step,this.x_unit),e.date[this.x_unit+"_start"]&&(a=e.date[this.x_unit+"_start"](a)),e._ignores[r]||i++,r++,t)if(i<this.x_size&&!(+n>+a))n=e.date["add_"+this.name+"_private"](n,(this.x_length||this.x_size)*this.x_step);else if(i>=this.x_size){e._max_date=a;break}return{total:r,displayed:i}}function d(t){var a=e.xy.scale_height,n=this._header_resized||e.xy.scale_height;

e._cols=[],e._colsS={height:0},this._trace_x=[];var i=e._x-this.dx-e.xy.scroll_width,r=[this.dx],l=e._els.dhx_cal_header[0];l.style.width=r[0]+i+"px";for(var d=e._min_date_timeline=e._min_date,s=e.config.preserve_scale_length,c=o.call(this,s),u=c.displayed,p=c.total,v=0;p>v;v++)e._ignores[v]?(e._cols[v]=0,u++):e._cols[v]=Math.floor(i/(u-v)),i-=e._cols[v],r[v+1]=r[v]+e._cols[v];if(t.innerHTML="<div></div>",this.second_scale){for(var m=this.second_scale.x_unit,g=[this._trace_x[0]],b=[],y=[this.dx,this.dx],f=0,x=0;x<this._trace_x.length;x++){
var k=this._trace_x[x],w=_(m,k,g[f]);w&&(++f,g[f]=k,y[f+1]=y[f]);var D=f+1;b[f]=e._cols[x]+(b[f]||0),y[D]+=e._cols[x]}t.innerHTML="<div></div><div></div>";var E=t.firstChild;E.style.height=n+"px";var M=t.lastChild;M.style.position="relative";for(var S=0;S<g.length;S++){var N=g[S],C=e.templates[this.name+"_second_scalex_class"](N),O=document.createElement("DIV");O.className="dhx_scale_bar dhx_second_scale_bar"+(C?" "+C:""),e.set_xy(O,b[S]-1,n-3,y[S],0),O.innerHTML=e.templates[this.name+"_second_scale_date"](N),
E.appendChild(O)}}e.xy.scale_height=n,t=t.lastChild;for(var T=0;T<this._trace_x.length;T++)if(!e._ignores[T]){d=this._trace_x[T],e._render_x_header(T,r[T],d,t);var z=e.templates[this.name+"_scalex_class"](d);z&&(t.lastChild.className+=" "+z)}e.xy.scale_height=a;var A=this._trace_x;t.onclick=function(t){var a=h(t);a&&e.callEvent("onXScaleClick",[a.x,A[a.x],t||event])},t.ondblclick=function(t){var a=h(t);a&&e.callEvent("onXScaleDblClick",[a.x,A[a.x],t||event])}}function _(t,a,n){switch(t){case"hour":
return a.getHours()!=n.getHours()||_("day",a,n);case"day":return!(a.getDate()==n.getDate()&&a.getMonth()==n.getMonth()&&a.getFullYear()==n.getFullYear());case"week":return!(e.date.getISOWeek(a)==e.date.getISOWeek(n)&&a.getFullYear()==n.getFullYear());case"month":return!(a.getMonth()==n.getMonth()&&a.getFullYear()==n.getFullYear());case"year":return!(a.getFullYear()==n.getFullYear());default:return!1}}function s(t){if(t){e.set_sizes(),e._init_matrix_tooltip();var a=e._min_date;d.call(this,e._els.dhx_cal_header[0]),
l.call(this,e._els.dhx_cal_data[0]),e._min_date=a,e._els.dhx_cal_date[0].innerHTML=e.templates[this.name+"_date"](e._min_date,e._max_date),e._mark_now&&e._mark_now()}c()}function c(){e._tooltip&&(e._tooltip.style.display="none",e._tooltip.date="")}function u(t,a,n){if("cell"==t.render){var i=a.x+"_"+a.y,r=t._matrix[a.y][a.x];if(!r)return c();if(r.sort(function(e,t){return e.start_date>t.start_date?1:-1}),e._tooltip){if(e._tooltip.date==i)return;e._tooltip.innerHTML=""}else{var l=e._tooltip=document.createElement("DIV");

l.className="dhx_year_tooltip",document.body.appendChild(l),l.onclick=e._click.dhx_cal_data}for(var o="",d=0;d<r.length;d++){var _=r[d].color?"background-color:"+r[d].color+";":"",s=r[d].textColor?"color:"+r[d].textColor+";":"";o+="<div class='dhx_tooltip_line' event_id='"+r[d].id+"' style='"+_+s+"'>",o+="<div class='dhx_tooltip_date'>"+(r[d]._timed?e.templates.event_date(r[d].start_date):"")+"</div>",o+="<div class='dhx_event_icon icon_details'>&nbsp;</div>",o+=e.templates[t.name+"_tooltip"](r[d].start_date,r[d].end_date,r[d])+"</div>";

}e._tooltip.style.display="",e._tooltip.style.top="0px",e._tooltip.style.left=document.body.offsetWidth-n.left-e._tooltip.offsetWidth<0?n.left-e._tooltip.offsetWidth+"px":n.left+a.src.offsetWidth+"px",e._tooltip.date=i,e._tooltip.innerHTML=o,e._tooltip.style.top=document.body.offsetHeight-n.top-e._tooltip.offsetHeight<0?n.top-e._tooltip.offsetHeight+a.src.offsetHeight+"px":n.top+"px"}}function p(e){for(var t=e.parentNode.childNodes,a=0;a<t.length;a++)if(t[a]==e)return a;return-1}function h(e){e=e||event;

for(var t=e.target?e.target:e.srcElement;t&&"DIV"!=t.tagName;)t=t.parentNode;if(t&&"DIV"==t.tagName){var a=t.className.split(" ")[0];if("dhx_scale_bar"==a)return{x:p(t),y:-1,src:t,scale:!0}}}e.matrix={},e._merge=function(e,t){for(var a in t)"undefined"==typeof e[a]&&(e[a]=t[a])},e.createTimelineView=function(t){e._skin_init(),e._merge(t,{section_autoheight:!0,name:"matrix",x:"time",y:"time",x_step:1,x_unit:"hour",y_unit:"day",y_step:1,x_start:0,x_size:24,y_start:0,y_size:7,render:"cell",dx:200,dy:50,
event_dy:e.xy.bar_height-5,event_min_dy:e.xy.bar_height-5,resize_events:!0,fit_events:!0,show_unassigned:!1,second_scale:!1,round_position:!1,_logic:function(t,a,n){var i={};return e.checkEvent("onBeforeSectionRender")&&(i=e.callEvent("onBeforeSectionRender",[t,a,n])),i}}),t._original_x_start=t.x_start,"day"!=t.x_unit&&(t.first_hour=t.last_hour=0),t._start_correction=t.first_hour?60*t.first_hour*60*1e3:0,t._end_correction=t.last_hour?60*(24-t.last_hour)*60*1e3:0,e.checkEvent("onTimelineCreated")&&e.callEvent("onTimelineCreated",[t]);

var a=e.render_data;e.render_data=function(n,i){if(this._mode!=t.name)return a.apply(this,arguments);if(i&&!t.show_unassigned&&"cell"!=t.render)for(var r=0;r<n.length;r++)this.clear_event(n[r]),this.render_timeline_event.call(this.matrix[this._mode],n[r],!0);else e._renderMatrix.call(t,!0,!0)},e.matrix[t.name]=t,e.templates[t.name+"_cell_value"]=function(e){return e?e.length:""},e.templates[t.name+"_cell_class"]=function(e){return""},e.templates[t.name+"_scalex_class"]=function(e){return""},e.templates[t.name+"_second_scalex_class"]=function(e){
return""},e.templates[t.name+"_scaley_class"]=function(e,t,a){return""},e.templates[t.name+"_scale_label"]=function(e,t,a){return t},e.templates[t.name+"_tooltip"]=function(e,t,a){return a.text},e.templates[t.name+"_date"]=function(t,a){return t.getDay()==a.getDay()&&864e5>a-t||+t==+e.date.date_part(new Date(a))||+e.date.add(t,1,"day")==+a&&0===a.getHours()&&0===a.getMinutes()?e.templates.day_date(t):t.getDay()!=a.getDay()&&864e5>a-t?e.templates.day_date(t)+" &ndash; "+e.templates.day_date(a):e.templates.week_date(t,a);

},e.templates[t.name+"_scale_date"]=e.date.date_to_str(t.x_date||e.config.hour_date),e.templates[t.name+"_second_scale_date"]=e.date.date_to_str(t.second_scale&&t.second_scale.x_date?t.second_scale.x_date:e.config.hour_date),e.date["add_"+t.name+"_private"]=function(a,n){var i=n,r=t.x_unit;if("minute"==t.x_unit||"hour"==t.x_unit){var l=i;"hour"==t.x_unit&&(l*=60),l%1440||(i=l/1440,r="day")}return e.date.add(a,i,r)},e.date["add_"+t.name]=function(a,n,i){var r=e.date["add_"+t.name+"_private"](a,(t.x_length||t.x_size)*t.x_step*n);

if("minute"==t.x_unit||"hour"==t.x_unit){var l=t.x_length||t.x_size,o="hour"==t.x_unit?60*t.x_step:t.x_step;if(o*l%1440)if(+e.date.date_part(new Date(a))==+e.date.date_part(new Date(r)))t.x_start+=n*l;else{var d=1440/(l*o)-1,_=Math.round(d*l);t.x_start=n>0?t.x_start-_:_+t.x_start}}return r},e.date[t.name+"_start"]=function(a){var n=e.date[t.x_unit+"_start"]||e.date.day_start,i=n.call(e.date,a);return i=e.date.add(i,t.x_step*t.x_start,t.x_unit)},e.callEvent("onOptionsLoad",[t]),e[t.name+"_view"]=function(a){
a?e._set_timeline_dates(t):e._renderMatrix.apply(t,arguments)};{var i=new Date;e.date.add(i,t.x_step,t.x_unit).valueOf()-i.valueOf()}e["mouse_"+t.name]=function(a){var i=this._drag_event;this._drag_id&&(i=this.getEvent(this._drag_id)),this._drag_pos&&this._is_pos_changed(this._drag_pos,a)&&(this._drag_event._dhx_changed=!0),a.x-=t.dx;var r=e._timeline_drag_date(t,a.x);if(a.x=0,a.force_redraw=!0,a.custom=!0,"move"==this._drag_mode&&this._drag_id&&this._drag_event){var i=this.getEvent(this._drag_id),l=this._drag_event;

if(a._ignores=this._ignores_detected||t._start_correction||t._end_correction,void 0===l._move_delta&&(l._move_delta=(i.start_date-r)/6e4,this.config.preserve_length&&a._ignores&&(l._move_delta=this._get_real_event_length(i.start_date,r,t),l._event_length=this._get_real_event_length(i.start_date,i.end_date,t))),this.config.preserve_length&&a._ignores){var o=(l._event_length,this._get_fictional_event_length(r,l._move_delta,t,!0));r=new Date(r-o)}else r=e.date.add(r,l._move_delta,"minute")}if("resize"==this._drag_mode&&i&&(this._drag_from_start&&+r>+i.end_date?this._drag_from_start=!1:!this._drag_from_start&&+r<+i.start_date&&(this._drag_from_start=!0),
a.resize_from_start=this._drag_from_start),t.round_position)switch(this._drag_mode){case"move":this.config.preserve_length||(r=n.call(t,r,!1),"day"==t.x_unit&&(a.custom=!1));break;case"resize":this._drag_event&&((null===this._drag_event._resize_from_start||void 0===this._drag_event._resize_from_start)&&(this._drag_event._resize_from_start=a.resize_from_start),a.resize_from_start=this._drag_event._resize_from_start,r=n.call(t,r,!this._drag_event._resize_from_start))}return this._resolve_timeline_section(t,a),
a.section&&this._update_timeline_section({pos:a,event:this.getEvent(this._drag_id),view:t}),a.y=Math.round((this._correct_shift(r,1)-this._min_date)/(6e4*this.config.time_step)),a.shift=this.config.time_step,a}},e._get_timeline_event_height=function(e,t){var a=e[t.y_property],n=t.event_dy;return"full"==t.event_dy&&(n=t.section_autoheight?t._section_height[a]-6:t.dy-3),t.resize_events&&(n=Math.max(Math.floor(n/e._count),t.event_min_dy)),n},e._get_timeline_event_y=function(t,a){var n=t,i=2+n*a+(n?2*n:0);

return e.config.cascade_event_display&&(i=2+n*e.config.cascade_event_margin+(n?2*n:0)),i},e.render_timeline_event=function(t,n){var i=t[this.y_property];if(!i)return"";var r=t._sorder,l=a(t,!1,this),o=a(t,!0,this),d=e._get_timeline_event_height(t,this),_=d-2;t._inner||"full"!=this.event_dy||(_=(_+2)*(t._count-r)-2);var s=e._get_timeline_event_y(t._sorder,d),c=d+s+2;(!this._events_height[i]||this._events_height[i]<c)&&(this._events_height[i]=c);var u=e.templates.event_class(t.start_date,t.end_date,t);

u="dhx_cal_event_line "+(u||""),t._no_drag_move&&(u+=" no_drag_move");var p=t.color?"background:"+t.color+";":"",h=t.textColor?"color:"+t.textColor+";":"",v=e.templates.event_bar_text(t.start_date,t.end_date,t),m='<div event_id="'+t.id+'" class="'+u+'" style="'+p+h+"position:absolute; top:"+s+"px; height: "+_+"px; left:"+l+"px; width:"+Math.max(0,o-l)+"px;"+(t._text_style||"")+'">';if(e.config.drag_resize&&!e.config.readonly){var g="dhx_event_resize",b="<div class='"+g+" "+g+"_start' style='height: "+_+"px;'></div>",y="<div class='"+g+" "+g+"_end' style='height: "+_+"px;'></div>";

m+=(t._no_resize_start?"":b)+(t._no_resize_end?"":y)}if(m+=v+"</div>",!n)return m;var f=document.createElement("DIV");f.innerHTML=m;var x=this.order[i],k=e._els.dhx_cal_data[0].firstChild.rows[x].cells[1].firstChild;e._rendered.push(f.firstChild),k.appendChild(f.firstChild)},e._matrix_tooltip_handler=function(t){var a=e.matrix[e._mode];if(a&&"cell"==a.render){if(a){{var n=e._locate_cell_timeline(t),t=t||event;t.target||t.srcElement}if(n)return u(a,n,getOffset(n.src))}c()}},e._init_matrix_tooltip=function(){
e._detachDomEvent(e._els.dhx_cal_data[0],"mouseover",e._matrix_tooltip_handler),dhtmlxEvent(e._els.dhx_cal_data[0],"mouseover",e._matrix_tooltip_handler)},e._set_timeline_dates=function(t){e._min_date=e.date[t.name+"_start"](new Date(e._date)),e._max_date=e.date["add_"+t.name+"_private"](e._min_date,t.x_size*t.x_step),e.date[t.x_unit+"_start"]&&(e._max_date=e.date[t.x_unit+"_start"](e._max_date)),e._table_view=!0},e._renderMatrix=function(t,a){if(a||(e._els.dhx_cal_data[0].scrollTop=0),e._set_timeline_dates(this),
this.second_scale&&(t&&!this._header_resized&&(this._header_resized=e.xy.scale_height,e.xy.scale_height*=2,e._els.dhx_cal_header[0].className+=" dhx_second_cal_header"),!t&&this._header_resized)){e.xy.scale_height/=2,this._header_resized=!1;var n=e._els.dhx_cal_header[0];n.className=n.className.replace(/ dhx_second_cal_header/gi,"")}s.call(this,t)},e._locate_cell_timeline=function(t){t=t||event;for(var a=t.target?t.target:t.srcElement,n={},i=e.matrix[e._mode],r=e.getActionData(t),l=0;l<i._trace_x.length-1&&!(+r.date<i._trace_x[l+1]);l++);
n.x=l,n.y=i.order[r.section];var o=e._isRender("cell")?1:0;n.src=i._scales[r.section]?i._scales[r.section].getElementsByTagName("td")[l+o]:null;for(var d=!1;0===n.x&&"dhx_cal_data"!=a.className&&a.parentNode;){if("dhx_matrix_scell"==a.className.split(" ")[0]){d=!0;break}a=a.parentNode}return d&&(n.x=-1,n.src=a,n.scale=!0),n};var v=e._click.dhx_cal_data;e._click.dhx_marked_timespan=e._click.dhx_cal_data=function(t){var a=v.apply(this,arguments),n=e.matrix[e._mode];if(n){var i=e._locate_cell_timeline(t);

i&&(i.scale?e.callEvent("onYScaleClick",[i.y,n.y_unit[i.y],t||event]):e.callEvent("onCellClick",[i.x,i.y,n._trace_x[i.x],(n._matrix[i.y]||{})[i.x]||[],t||event]))}return a},e.dblclick_dhx_matrix_cell=function(t){var a=e.matrix[e._mode];if(a){var n=e._locate_cell_timeline(t);n&&(n.scale?e.callEvent("onYScaleDblClick",[n.y,a.y_unit[n.y],t||event]):e.callEvent("onCellDblClick",[n.x,n.y,a._trace_x[n.x],(a._matrix[n.y]||{})[n.x]||[],t||event]))}};var m=e.dblclick_dhx_marked_timespan||function(){};e.dblclick_dhx_marked_timespan=function(t){
var a=e.matrix[e._mode];return a?e.dblclick_dhx_matrix_cell(t):m.apply(this,arguments)},e.dblclick_dhx_matrix_scell=function(t){return e.dblclick_dhx_matrix_cell(t)},e._isRender=function(t){return e.matrix[e._mode]&&e.matrix[e._mode].render==t},e.attachEvent("onCellDblClick",function(t,a,n,i,r){if(!this.config.readonly&&("dblclick"!=r.type||this.config.dblclick_create)){var l=e.matrix[e._mode],o={};o.start_date=l._trace_x[t],o.end_date=l._trace_x[t+1]?l._trace_x[t+1]:e.date.add(l._trace_x[t],l.x_step,l.x_unit),
l._start_correction&&(o.start_date=new Date(1*o.start_date+l._start_correction)),l._end_correction&&(o.end_date=new Date(o.end_date-l._end_correction)),o[l.y_property]=l.y_unit[a].key,e.addEventNow(o,null,r)}}),e.attachEvent("onBeforeDrag",function(t,a,n){return!e._isRender("cell")}),e.attachEvent("onEventChanged",function(e,t){t._timed=this.isOneDayEvent(t)}),e.attachEvent("onBeforeEventChanged",function(t,a,n,i){return e._events[t.id]&&(t._move_delta=void 0),!0}),e._is_column_visible=function(t){
var a=e.matrix[e._mode],n=e._get_date_index(a,t);return!e._ignores[n]};var g=e._render_marked_timespan;e._render_marked_timespan=function(t,n,i,r,l){if(!e.config.display_marked_timespans)return[];if(e.matrix&&e.matrix[e._mode]){if(e._isRender("cell"))return;var o=e._lame_copy({},e.matrix[e._mode]);o.round_position=!1;var d=[],_=[],s=[],c=t.sections?t.sections.units||t.sections.timeline:null;if(i)s=[n],_=[i];else{var u=o.order;if(c)u.hasOwnProperty(c)&&(_.push(c),s.push(o._scales[c]));else for(var p in u)u.hasOwnProperty(p)&&(_.push(p),
s.push(o._scales[p]))}var r=r?new Date(r):e._min_date,l=l?new Date(l):e._max_date;r.valueOf()<e._min_date.valueOf()&&(r=new Date(e._min_date)),l.valueOf()>e._max_date.valueOf()&&(l=new Date(e._max_date));for(var h=0;h<o._trace_x.length&&!e._is_column_visible(o._trace_x[h]);h++);if(h==o._trace_x.length)return;var v=[];if(t.days>6){var m=new Date(t.days);e.date.date_part(new Date(r))<=+m&&+l>=+m&&v.push(m)}else v.push.apply(v,e._get_dates_by_index(t.days));for(var b=t.zones,y=e._get_css_classes_by_config(t),f=0;f<_.length;f++){
n=s[f],i=_[f];for(var h=0;h<v.length;h++)for(var x=v[h],k=0;k<b.length;k+=2){var w=b[k],D=b[k+1],E=new Date(+x+60*w*1e3),M=new Date(+x+60*D*1e3);if(M>r&&l>E){var S=e._get_block_by_config(t);S.className=y;var N=a({start_date:E},!1,o)-1,C=a({start_date:M},!1,o)-1,O=Math.max(1,C-N-1),T=o._section_height[i]-1;S.style.cssText="height: "+T+"px; left: "+N+"px; width: "+O+"px; top: 0;",n.insertBefore(S,n.firstChild),d.push(S)}}}return d}return g.apply(e,[t,n,i])};var b=e._append_mark_now;e._append_mark_now=function(t,a){
if(e.matrix&&e.matrix[e._mode]){var n=e._currentDate(),i=e._get_zone_minutes(n),r={days:+e.date.date_part(n),zones:[i,i+1],css:"dhx_matrix_now_time",type:"dhx_now_time"};return e._render_marked_timespan(r)}return b.apply(e,[t,a])};var y=e._mark_timespans;e._mark_timespans=function(){if(e.matrix&&e.matrix[e.getState().mode]){for(var t=[],a=e.matrix[e.getState().mode],n=a.y_unit,i=0;i<n.length;i++){var r=n[i].key,l=a._scales[r],o=e._on_scale_add_marker(l,r);t.push.apply(t,o)}return t}return y.apply(this,arguments);

};var f=e._on_scale_add_marker;e._on_scale_add_marker=function(t,a){if(e.matrix&&e.matrix[e._mode]){var n=[],i=e._marked_timespans;if(i&&e.matrix&&e.matrix[e._mode])for(var r=e._mode,l=e._min_date,o=e._max_date,d=i.global,_=e.date.date_part(new Date(l));o>_;_=e.date.add(_,1,"day")){var s=+_,c=_.getDay(),u=[],p=d[s]||d[c];if(u.push.apply(u,e._get_configs_to_render(p)),i[r]&&i[r][a]){var h=[],v=e._get_types_to_render(i[r][a][c],i[r][a][s]);h.push.apply(h,e._get_configs_to_render(v)),h.length&&(u=h);

}for(var m=0;m<u.length;m++){var g=u[m],b=g.days;7>b?(b=s,n.push.apply(n,e._render_marked_timespan(g,t,a,_,e.date.add(_,1,"day"))),b=c):n.push.apply(n,e._render_marked_timespan(g,t,a,_,e.date.add(_,1,"day")))}}return n}return f.apply(this,arguments)},e._resolve_timeline_section=function(e,t){var a=0,n=0;for(a;a<this._colsS.heights.length&&(n+=this._colsS.heights[a],!(n>t.y));a++);e.y_unit[a]||(a=e.y_unit.length-1),this._drag_event&&!this._drag_event._orig_section&&(this._drag_event._orig_section=e.y_unit[a].key),
t.fields={},a>=0&&e.y_unit[a]&&(t.section=t.fields[e.y_property]=e.y_unit[a].key)},e._update_timeline_section=function(e){var t=e.view,a=e.event,n=e.pos;if(a){if(a[t.y_property]!=n.section){var i=this._get_timeline_event_height(a,t);a._sorder=this._get_dnd_order(a._sorder,i,t._section_height[n.section])}a[t.y_property]=n.section}},e._get_date_index=function(e,t){for(var a=0,n=e._trace_x;a<n.length-1&&+t>=+n[a+1];)a++;return a},e._timeline_drag_date=function(t,a){var n,i,r=t,l={x:a},o=0,d=0;for(d;d<=this._cols.length-1;d++)if(i=this._cols[d],
o+=i,o>l.x){n=(l.x-(o-i))/i,n=0>n?0:n;break}if(r.round_position){var _=1;e.getState().drag_mode&&"move"!=e.getState().drag_mode&&(_=.5),n>=_&&d++,n=0}if(0===d&&this._ignores[0])for(d=1,n=0;this._ignores[d];)d++;else if(d==this._cols.length&&this._ignores[d-1]){for(d=this._cols.length-1,n=0;this._ignores[d];)d--;d++}var s;if(d>=r._trace_x.length)s=e.date.add(r._trace_x[r._trace_x.length-1],r.x_step,r.x_unit),r._end_correction&&(s=new Date(s-r._end_correction));else{var c=n*i*r._step+r._start_correction;

s=new Date(+r._trace_x[d]+c)}return s},e.attachEvent("onBeforeTodayDisplayed",function(){for(var t in e.matrix){var a=e.matrix[t];a.x_start=a._original_x_start}return!0}),e.attachEvent("onOptionsLoad",function(){for(var t in e.matrix){var a=e.matrix[t];a.order={},e.callEvent("onOptionsLoadStart",[]);for(var t=0;t<a.y_unit.length;t++)a.order[a.y_unit[t].key]=t;e.callEvent("onOptionsLoadFinal",[]),e._date&&a.name==e._mode&&e.setCurrentView(e._date,e._mode)}}),e.attachEvent("onSchedulerResize",function(){
if(e.matrix[this._mode]){var t=e.matrix[this._mode];return e._renderMatrix.call(t,!0,!0),!1}return!0}),e.attachEvent("onBeforeDrag",function(t,a,n){if("resize"==a){var i=n.target||n.srcElement;e._drag_from_start=(i.className||"").indexOf("dhx_event_resize_end")<0?!0:!1}return!0})},e._temp_matrix_scope()});