/*
@license
dhtmlxScheduler.Net v.3.3.4 

This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Scheduler._external_drag={from_scheduler:null,to_scheduler:null,drag_data:null,drag_placeholder:null,delete_dnd_holder:function(){var e=this.drag_placeholder;e&&(e.parentNode&&e.parentNode.removeChild(e),document.body.className=document.body.className.replace(" dhx_no_select",""),this.drag_placeholder=null)},copy_event_node:function(e,a){for(var t=null,l=0;l<a._rendered.length;l++){var n=a._rendered[l];if(n.getAttribute("event_id")==e.id||n.getAttribute("event_id")==a._drag_id){t=n.cloneNode(!0),
t.style.position=t.style.top=t.style.left="";break}}return t||document.createElement("div")},create_dnd_holder:function(e,a){if(this.drag_placeholder)return this.drag_placeholder;var t=document.createElement("div"),l=a.templates.event_outside(e.start_date,e.end_date,e);return l?t.innerHTML=l:t.appendChild(this.copy_event_node(e,a)),t.className="dhx_drag_placeholder",t.style.position="absolute",this.drag_placeholder=t,document.body.appendChild(t),document.body.className+=" dhx_no_select",t},move_dnd_holder:function(e){
var a={x:e.clientX,y:e.clientY};if(this.create_dnd_holder(this.drag_data.ev,this.from_scheduler),this.drag_placeholder){var t=a.x,l=a.y,n=document.documentElement,i=document.body,o=this.drag_placeholder;o.style.left=10+t+(n&&n.scrollLeft||i&&i.scrollLeft||0)-(n.clientLeft||0)+"px",o.style.top=10+l+(n&&n.scrollTop||i&&i.scrollTop||0)-(n.clientTop||0)+"px"}},clear_scheduler_dnd:function(e){e._drag_id=e._drag_mode=e._drag_event=e._new_event=null},stop_drag:function(e){e&&this.clear_scheduler_dnd(e),
this.delete_dnd_holder(),this.drag_data=null},inject_into_scheduler:function(e,a,t){e._count=1,e._sorder=0,e.event_pid&&"0"!=e.event_pid&&(e.event_pid=null,e.rec_type=e.rec_pattern="",e.event_length=0),a._drag_event=e,a._events[e.id]=e,a._drag_id=e.id,a._drag_mode="move",t&&a._on_mouse_move(t)},start_dnd:function(e){if(e.config.drag_out){this.from_scheduler=e,this.to_scheduler=e;var a=this.drag_data={};a.ev=e._drag_event,a.orig_id=e._drag_event.id}},land_into_scheduler:function(e,a){if(!e.config.drag_in)return this.move_dnd_holder(a),
!1;var t=this.drag_data,l=e._lame_clone(t.ev);if(e!=this.from_scheduler){l.id=e.uid();var n=l.end_date-l.start_date;l.start_date=new Date(e.getState().min_date),l.end_date=new Date(l.start_date.valueOf()+n)}else l.id=this.drag_data.orig_id,l._dhx_changed=!0;return this.drag_data.target_id=l.id,e.callEvent("onBeforeEventDragIn",[l.id,l,a])?(this.to_scheduler=e,this.inject_into_scheduler(l,e,a),this.delete_dnd_holder(),e.updateView(),e.callEvent("onEventDragIn",[l.id,l,a]),!0):!1},drag_from_scheduler:function(e,a){
if(this.drag_data&&e._drag_id&&e.config.drag_out){if(this.to_scheduler==e&&(this.to_scheduler=null),!e.callEvent("onBeforeEventDragOut",[e._drag_id,e._drag_event,a]))return!1;this.create_dnd_holder(this.drag_data.ev,e);var t=e._drag_id;return this.drag_data.target_id=null,delete e._events[t],this.clear_scheduler_dnd(e),e.updateEvent(t),e.callEvent("onEventDragOut",[t,this.drag_data.ev,a]),!0}return!1},reset_event:function(e,a){this.inject_into_scheduler(e,a),this.stop_drag(a),a.updateView()},move_permanently:function(e,a,t,l){
l.callEvent("onEventAdded",[a.id,a]),this.inject_into_scheduler(e,t),this.stop_drag(t),e.event_pid&&"0"!=e.event_pid?(t.callEvent("onConfirmedBeforeEventDelete",[e.id]),t.updateEvent(a.event_pid)):t.deleteEvent(e.id),t.updateView(),l.updateView()}},dhtmlxEvent(window,"load",function(){dhtmlxEvent(document.body,"mousemove",function(e){var a=Scheduler._external_drag,t=a.target_scheduler;if(t)if(a.from_scheduler)if(t._drag_id);else{var l=a.to_scheduler;(!l||a.drag_from_scheduler(l,e))&&a.land_into_scheduler(t,e);

}else"move"==t.getState().drag_mode&&t.config.drag_out&&a.start_dnd(t);else a.from_scheduler&&(a.to_scheduler?a.drag_from_scheduler(a.to_scheduler,e):a.move_dnd_holder(e));a.target_scheduler=null}),dhtmlxEvent(document.body,"mouseup",function(e){var a=Scheduler._external_drag,t=a.from_scheduler,l=a.to_scheduler;if(t)if(l&&t==l)t.updateEvent(a.drag_data.target_id);else if(l&&t!==l){var n=a.drag_data.ev,i=l.getEvent(a.drag_data.target_id);t.callEvent("onEventDropOut",[n.id,n,l,e])?a.move_permanently(n,i,t,l):a.reset_event(n,t);

}else{var n=a.drag_data.ev;t.callEvent("onEventDropOut",[n.id,n,null,e])&&a.reset_event(n,t)}a.stop_drag(),a.current_scheduler=a.from_scheduler=a.to_scheduler=null})}),Scheduler.plugin(function(e){e.config.drag_in=!0,e.config.drag_out=!0,e.templates.event_outside=function(e,a,t){};var a=Scheduler._external_drag;e.attachEvent("onTemplatesReady",function(){dhtmlxEvent(e._obj,"mousemove",function(t){a.target_scheduler=e}),dhtmlxEvent(e._obj,"mouseup",function(t){a.target_scheduler=e})})});