/*
@license
dhtmlxScheduler.Net v.3.3.4 

This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Scheduler.plugin(function(e){!function(){e._register_copies_array=function(e){for(var a=0;a<e.length;a++)this._register_copy(e[a])},e._register_copy=function(e){this._multisection_copies[e.id]||(this._multisection_copies[e.id]={});var a=e[this._get_section_property()],t=this._multisection_copies[e.id];t[a]||(t[a]=e)},e._get_copied_event=function(a,t){if(!this._multisection_copies[a])return null;if(this._multisection_copies[a][t])return this._multisection_copies[a][t];var l=this._multisection_copies[a];

if(e._drag_event&&e._drag_event._orig_section&&l[e._drag_event._orig_section])return l[e._drag_event._orig_section];var n=1/0,i=null;for(var o in l)l[o]._sorder<n&&(i=l[o],n=l[o]._sorder);return i},e._clear_copied_events=function(){this._multisection_copies={}},e._restore_render_flags=function(a){for(var t=this._get_section_property(),l=0;l<a.length;l++){var n=a[l],i=e._get_copied_event(n.id,n[t]);if(i)for(var o in i)0===o.indexOf("_")&&(n[o]=i[o])}};var a=e.createTimelineView;e.createTimelineView=function(t){
function l(){var a=new Date(e.getState().date),l=e.date[u+"_start"](a);l=e.date.date_part(l);var n=[],i=e.matrix[u];i.y_unit=n,i.order={};for(var o=0;o<t.days;o++)n.push({key:+l,label:l}),i.order[i.y_unit[o].key]=o,l=e.date.add(l,1,"day")}function n(e){var a={};for(var t in e)a[t]=e[t];return a}function i(e,a){a.setFullYear(e.getFullYear()),a.setMonth(e.getMonth()),a.setDate(e.getDate())}function o(a){for(var t=[],l=0;l<a.length;l++){var n=d(a[l]);if(e.isOneDayEvent(n))_(n),t.push(n);else{for(var i=new Date(Math.min(+n.end_date,+e._max_date)),o=new Date(Math.max(+n.start_date,+e._min_date)),p=[];+i>+o;){
var u=d(n);u.start_date=o,u.end_date=new Date(Math.min(+c(u.start_date),+i)),o=c(o),_(u),t.push(u),p.push(u)}r(p,n)}}return t}function r(e,a){for(var t=!1,l=!1,n=0,i=e.length;i>n;n++){var o=e[n];t=+o._w_start_date==+a.start_date,l=+o._w_end_date==+a.end_date,o._no_resize_start=o._no_resize_end=!0,t&&(o._no_resize_start=!1),l&&(o._no_resize_end=!1)}}function d(a){var t=e.getEvent(a.event_pid);return t&&t.isPrototypeOf(a)?(a=e._copy_event(a),delete a.event_length,delete a.event_pid,delete a.rec_pattern,
delete a.rec_type):a=e._lame_clone(a),a}function _(a){if(!a._w_start_date||!a._w_end_date){var t=e.date,l=a._w_start_date=new Date(a.start_date),n=a._w_end_date=new Date(a.end_date);a[s]=+t.date_part(a.start_date),a._count||(a._count=1),a._sorder||(a._sorder=0);var i=n-l;a.start_date=new Date(e._min_date),p(l,a.start_date),a.end_date=new Date(+a.start_date+i)}}function p(e,a){a.setMinutes(e.getMinutes()),a.setHours(e.getHours())}function c(a){var t=e.date.add(a,1,"day");return t=e.date.date_part(t);

}if("days"!=t.render)return void a.apply(this,arguments);var u=t.name,s=t.y_property="timeline-week"+u;t.y_unit=[],t.render="bar",t.days=t.days||7,a.call(this,t),e.templates[u+"_scalex_class"]=function(){},e.templates[u+"_scaley_class"]=function(){},e.templates[u+"_scale_label"]=function(a,t,l){return e.templates.day_date(t)},e.date[u+"_start"]=function(a){return a=e.date.week_start(a),a=e.date.add(a,t.x_step*t.x_start,t.x_unit)},e.date["add_"+u]=function(a,l){return e.date.add(a,l*t.days,"day")};

var v=e._renderMatrix;e._renderMatrix=function(e,a){e&&l(),v.apply(this,arguments)};var b=e.checkCollision;e.checkCollision=function(a){if(a[s]){var a=n(a);delete a[s]}return b.apply(e,[a])},e.attachEvent("onBeforeDrag",function(a,t,l){var n=l.target||l.srcElement,i=n.className||"";if("resize"==t)e._w_line_drag_from_start=i.indexOf("dhx_event_resize_end")<0?!0:!1;else if("move"==t&&i.indexOf("no_drag_move")>=0)return!1;return!0});var h=e["mouse_"+u];e["mouse_"+u]=function(a){var t;if(this._drag_event&&(t=this._drag_event._move_delta),
void 0===t&&"move"==e._drag_mode){var l=e.matrix[this._mode],n={y:a.y};e._resolve_timeline_section(l,n);var i=a.x-l.dx,o=new Date(n.section);p(e._timeline_drag_date(l,i),o);var r=e._drag_event,d=this.getEvent(this._drag_id);r._move_delta=(d.start_date-o)/6e4,this.config.preserve_length&&a._ignores&&(r._move_delta=this._get_real_event_length(d.start_date,o,l),r._event_length=this._get_real_event_length(d.start_date,d.end_date,l))}var a=h.apply(e,arguments);if(e._drag_mode&&"move"!=e._drag_mode){var _=null;

_=new Date(e._drag_event&&e._drag_event["timeline-week"+u]?e._drag_event["timeline-week"+u]:a.section),a.y+=Math.round((_-e.date.date_part(new Date(e._min_date)))/(6e4*this.config.time_step)),"resize"==e._drag_mode&&(a.resize_from_start=e._w_line_drag_from_start)}else if(e._drag_event){var c=Math.floor(Math.abs(a.y/(1440/e.config.time_step)));c*=a.y>0?1:-1,a.y=a.y%(1440/e.config.time_step);var s=e.date.date_part(new Date(e._min_date));s.valueOf()!=new Date(a.section).valueOf()&&(a.x=Math.floor((a.section-s)/864e5),
a.x+=c)}return a},e.attachEvent("onEventCreated",function(a,t){return e._events[a]&&delete e._events[a][s],!0}),e.attachEvent("onBeforeEventChanged",function(a,t,l,n){return e._events[a.id]&&delete e._events[a.id][s],!0});var m=e.render_view_data;e.render_view_data=function(a,t){return this._mode==u&&a&&(a=o(a),e._restore_render_flags(a)),m.apply(e,[a,t])};var y=e.get_visible_events;e.get_visible_events=function(){if(this._mode==u){this._clear_copied_events(),e._max_date=e.date.date_part(e.date.add(e._min_date,t.days,"day"));

var a=y.apply(e,arguments);return a=o(a),e._register_copies_array(a),a}return y.apply(e,arguments)};var x=e.addEventNow;e.addEventNow=function(a){if(e.getState().mode==u)if(a[s]){var t=new Date(a[s]);i(t,a.start_date),i(t,a.end_date)}else{var l=new Date(a.start_date);a[s]=+e.date.date_part(l)}return x.apply(e,arguments)};var g=e._render_marked_timespan;e._render_marked_timespan=function(){return e._mode!=u?g.apply(this,arguments):void 0}}}()});