/*
@license
dhtmlxScheduler.Net v.3.3.4 

This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Scheduler.plugin(function(e){e.form_blocks.combo={render:function(e){e.cached_options||(e.cached_options={});var a="";return a+="<div class='"+e.type+"' style='height:"+(e.height||20)+"px;' ></div>"},set_value:function(a,t,n,l){!function(){function t(){if(a._combo&&a._combo.DOMParent){var e=a._combo;e.unload?e.unload():e.destructor&&e.destructor(),e.DOMParent=e.DOMelem=null}}t();var n=e.attachEvent("onAfterLightbox",function(){t(),e.detachEvent(n)})}(),window.dhx_globalImgPath=l.image_path||"/",a._combo=new dhtmlXCombo(a,l.name,a.offsetWidth-8),
l.onchange&&a._combo.attachEvent("onChange",l.onchange),l.options_height&&a._combo.setOptionHeight(l.options_height);var i=a._combo;if(i.enableFilteringMode(l.filtering,l.script_path||null,!!l.cache),l.script_path){var o=n[l.map_to];o?l.cached_options[o]?(i.addOption(o,l.cached_options[o]),i.disable(1),i.selectOption(0),i.disable(0)):dhtmlxAjax.get(l.script_path+"?id="+o+"&uid="+e.uid(),function(e){var a=e.doXPath("//option")[0],t=a.childNodes[0].nodeValue;l.cached_options[o]=t,i.addOption(o,t),i.disable(1),
i.selectOption(0),i.disable(0)}):i.setComboValue("")}else{for(var r=[],d=0;d<l.options.length;d++){var _=l.options[d],c=[_.key,_.label,_.css];r.push(c)}if(i.addOption(r),n[l.map_to]){var p=i.getIndexByValue(n[l.map_to]);i.selectOption(p)}}},get_value:function(e,a,t){var n=e._combo.getSelectedValue();return t.script_path&&(t.cached_options[n]=e._combo.getSelectedText()),n},focus:function(e){}},e.form_blocks.radio={render:function(a){var t="";t+="<div class='dhx_cal_ltext dhx_cal_radio' style='height:"+a.height+"px;' >";

for(var n=0;n<a.options.length;n++){var l=e.uid();t+="<input id='"+l+"' type='radio' name='"+a.name+"' value='"+a.options[n].key+"'><label for='"+l+"'> "+a.options[n].label+"</label>",a.vertical&&(t+="<br/>")}return t+="</div>"},set_value:function(e,a,t,n){for(var l=e.getElementsByTagName("input"),i=0;i<l.length;i++){l[i].checked=!1;var o=t[n.map_to]||a;l[i].value==o&&(l[i].checked=!0)}},get_value:function(e,a,t){for(var n=e.getElementsByTagName("input"),l=0;l<n.length;l++)if(n[l].checked)return n[l].value;

},focus:function(e){}},e.form_blocks.checkbox={render:function(a){return e.config.wide_form?'<div class="dhx_cal_wide_checkbox" '+(a.height?"style='height:"+a.height+"px;'":"")+"></div>":""},set_value:function(a,t,n,l){a=document.getElementById(l.id);var i=e.uid(),o="undefined"!=typeof l.checked_value?t==l.checked_value:!!t;a.className+=" dhx_cal_checkbox";var r="<input id='"+i+"' type='checkbox' value='true' name='"+l.name+"'"+(o?"checked='true'":"")+"'>",d="<label for='"+i+"'>"+(e.locale.labels["section_"+l.name]||l.name)+"</label>";

if(e.config.wide_form?(a.innerHTML=d,a.nextSibling.innerHTML=r):a.innerHTML=r+d,l.handler){var _=a.getElementsByTagName("input")[0];_.onclick=l.handler}},get_value:function(e,a,t){e=document.getElementById(t.id);var n=e.getElementsByTagName("input")[0];return n||(n=e.nextSibling.getElementsByTagName("input")[0]),n.checked?t.checked_value||!0:t.unchecked_value||!1},focus:function(e){}}});