/*
@license
dhtmlxScheduler.Net v.3.3.4 

This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Scheduler.plugin(function(e){!function(){e._grid={sort_rules:{"int":function(e,a,t){return 1*t(e)<1*t(a)?1:-1},str:function(e,a,t){return t(e)<t(a)?1:-1},date:function(e,a,t){return new Date(t(e))<new Date(t(a))?1:-1}},_getObjName:function(e){return"grid_"+e},_getViewName:function(e){return e.replace(/^grid_/,"")}}}(),e.createGridView=function(a){function t(e){return!(void 0!==e&&(1*e!=e||0>e))}var n=a.name||"grid",l=e._grid._getObjName(n);e.config[n+"_start"]=a.from||new Date(0),e.config[n+"_end"]=a.to||new Date(9999,1,1),
e[l]=a,e[l].defPadding=8,e[l].columns=e[l].fields,e[l].unit=a.unit||"month",e[l].step=a.step||1,delete e[l].fields;for(var i=e[l].columns,o=0;o<i.length;o++)t(i[o].width)&&(i[o].initialWidth=i[o].width),t(i[o].paddingLeft)||delete i[o].paddingLeft,t(i[o].paddingRight)||delete i[o].paddingRight;e[l].select=void 0===a.select?!0:a.select,void 0===e.locale.labels[n+"_tab"]&&(e.locale.labels[n+"_tab"]=e[l].label||e.locale.labels.grid_tab),e[l]._selected_divs=[],e.date[n+"_start"]=function(t){return e.date[a.unit+"_start"]?e.date[a.unit+"_start"](t):t;

},e.date["add_"+n]=function(a,t){return e.date.add(a,t*e[l].step,e[l].unit)},e.templates[n+"_date"]=function(a,t){return e.templates.day_date(a)+" - "+e.templates.day_date(t)},e.templates[n+"_full_date"]=function(a,t,l){return e.isOneDayEvent(l)?this[n+"_single_date"](a):e.templates.day_date(a)+" &ndash; "+e.templates.day_date(t)},e.templates[n+"_single_date"]=function(a){return e.templates.day_date(a)+" "+this.event_date(a)},e.templates[n+"_field"]=function(e,a){return a[e]},e.attachEvent("onTemplatesReady",function(){
e.attachEvent("onDblClick",function(a,t){return this._mode==n?(e._click.buttons.details(a),!1):!0}),e.attachEvent("onClick",function(a,t){return this._mode==n&&e[l].select?(e._grid.unselectEvent("",n),e._grid.selectEvent(a,n,t),!1):!0});var a=e.render_data;e.render_data=function(t){return this._mode!=n?a.apply(this,arguments):void e._grid._fill_grid_tab(l)};var t=e.render_view_data;e.render_view_data=function(){var a=e._els.dhx_cal_data[0].lastChild;return this._mode==n&&a&&(e._grid._gridScrollTop=a.scrollTop),
t.apply(this,arguments)}}),e[n+"_view"]=function(a){if(e._grid._sort_marker=null,delete e._gridView,e._grid._gridScrollTop=0,e._rendered=[],e[l]._selected_divs=[],a){var t=null,i=null,o=e[l];o.paging?(t=e.date[n+"_start"](new Date(e._date)),i=e.date["add_"+n](t,1)):(t=e.config[n+"_start"],i=e.config[n+"_end"]),e._min_date=t,e._max_date=i,e._grid.set_full_view(l);var r="";+t>+new Date(0)&&+i<+new Date(9999,1,1)&&(r=e.templates[n+"_date"](t,i)),e._els.dhx_cal_date[0].innerHTML=r,e._gridView=l}}},e.dblclick_dhx_grid_area=function(){
!this.config.readonly&&this.config.dblclick_create&&this.addEventNow()},e._click.dhx_cal_header&&(e._old_header_click=e._click.dhx_cal_header),e._click.dhx_cal_header=function(a){if(e._gridView){var t=a||window.event,n=e._grid.get_sort_params(t,e._gridView);e._grid.draw_sort_marker(t.originalTarget||t.srcElement,n.dir),e.clear_view(),e._grid._fill_grid_tab(e._gridView,n)}else if(e._old_header_click)return e._old_header_click.apply(this,arguments)},e._grid.selectEvent=function(a,t,n){if(e.callEvent("onBeforeRowSelect",[a,n])){
var l=e._grid._getObjName(t);e.for_rendered(a,function(a){a.className+=" dhx_grid_event_selected",e[l]._selected_divs.push(a)}),e._select_id=a}},e._grid._unselectDiv=function(e){e.className=e.className.replace(/ dhx_grid_event_selected/,"")},e._grid.unselectEvent=function(a,t){var n=e._grid._getObjName(t);if(n&&e[n]._selected_divs)if(a){for(var l=0;l<e[n]._selected_divs.length;l++)if(e[n]._selected_divs[l].getAttribute("event_id")==a){e._grid._unselectDiv(e[n]._selected_divs[l]),e[n]._selected_divs.slice(l,1);

break}}else{for(var l=0;l<e[n]._selected_divs.length;l++)e._grid._unselectDiv(e[n]._selected_divs[l]);e[n]._selected_divs=[]}},e._grid.get_sort_params=function(a,t){var n=a.originalTarget||a.srcElement,l="desc";"dhx_grid_view_sort"==n.className&&(n=n.parentNode),n.className&&-1!=n.className.indexOf("dhx_grid_sort_asc")||(l="asc");for(var i=0,o=0;o<n.parentNode.childNodes.length;o++)if(n.parentNode.childNodes[o]==n){i=o;break}var r=null;if(e[t].columns[i].template){var d=e[t].columns[i].template;r=function(e){
return d(e.start_date,e.end_date,e)}}else{var _=e[t].columns[i].id;"date"==_&&(_="start_date"),r=function(e){return e[_]}}var c=e[t].columns[i].sort;return"function"!=typeof c&&(c=e._grid.sort_rules[c]||e._grid.sort_rules.str),{dir:l,value:r,rule:c}},e._grid.draw_sort_marker=function(a,t){"dhx_grid_view_sort"==a.className&&(a=a.parentNode),e._grid._sort_marker&&(e._grid._sort_marker.className=e._grid._sort_marker.className.replace(/( )?dhx_grid_sort_(asc|desc)/,""),e._grid._sort_marker.removeChild(e._grid._sort_marker.lastChild)),
a.className+=" dhx_grid_sort_"+t,e._grid._sort_marker=a;var n="<div class='dhx_grid_view_sort' style='left:"+(+a.style.width.replace("px","")-15+a.offsetLeft)+"px'>&nbsp;</div>";a.innerHTML+=n},e._grid.sort_grid=function(a){var a=a||{dir:"desc",value:function(e){return e.start_date},rule:e._grid.sort_rules.date},t=e.get_visible_events();return t.sort("desc"==a.dir?function(e,t){return a.rule(e,t,a.value)}:function(e,t){return-a.rule(e,t,a.value)}),t},e._grid.set_full_view=function(a){if(a){var t=(e.locale.labels,
e._grid._print_grid_header(a));e._els.dhx_cal_header[0].innerHTML=t,e._table_view=!0,e.set_sizes()}},e._grid._calcPadding=function(a,t){var n=(void 0!==a.paddingLeft?1*a.paddingLeft:e[t].defPadding)+(void 0!==a.paddingRight?1*a.paddingRight:e[t].defPadding);return n},e._grid._getStyles=function(e,a){for(var t=[],n="",l=0;a[l];l++)switch(n=a[l]+":",a[l]){case"text-align":e.align&&t.push(n+e.align);break;case"vertical-align":e.valign&&t.push(n+e.valign);break;case"padding-left":void 0!==e.paddingLeft&&t.push(n+(e.paddingLeft||"0")+"px");

break;case"padding-right":void 0!==e.paddingRight&&t.push(n+(e.paddingRight||"0")+"px")}return t},e._grid._fill_grid_tab=function(a,t){for(var n=(e._date,e._grid.sort_grid(t)),l=e[a].columns,i="<div>",o=-2,r=0;r<l.length;r++){var d=e._grid._calcPadding(l[r],a);o+=l[r].width+d,r<l.length-1&&(i+="<div class='dhx_grid_v_border' style='left:"+o+"px'></div>")}i+="</div>",i+="<div class='dhx_grid_area'><table>";for(var r=0;r<n.length;r++)i+=e._grid._print_event_row(n[r],a);i+="</table></div>",e._els.dhx_cal_data[0].innerHTML=i,
e._els.dhx_cal_data[0].lastChild.scrollTop=e._grid._gridScrollTop||0;var _=e._els.dhx_cal_data[0].getElementsByTagName("tr");e._rendered=[];for(var r=0;r<_.length;r++)e._rendered[r]=_[r]},e._grid._print_event_row=function(a,t){var n=[];a.color&&n.push("background:"+a.color),a.textColor&&n.push("color:"+a.textColor),a._text_style&&n.push(a._text_style),e[t].rowHeight&&n.push("height:"+e[t].rowHeight+"px");var l="";n.length&&(l="style='"+n.join(";")+"'");for(var i=e[t].columns,o=e.templates.event_class(a.start_date,a.end_date,a),r="<tr class='dhx_grid_event"+(o?" "+o:"")+"' event_id='"+a.id+"' "+l+">",d=e._grid._getViewName(t),_=["text-align","vertical-align","padding-left","padding-right"],c=0;c<i.length;c++){
var s;s=i[c].template?i[c].template(a.start_date,a.end_date,a):"date"==i[c].id?e.templates[d+"_full_date"](a.start_date,a.end_date,a):"start_date"==i[c].id||"end_date"==i[c].id?e.templates[d+"_single_date"](a[i[c].id]):e.templates[d+"_field"](i[c].id,a);var p=e._grid._getStyles(i[c],_),u=i[c].css?' class="'+i[c].css+'"':"";r+="<td style='width:"+i[c].width+"px;"+p.join(";")+"' "+u+">"+s+"</td>"}return r+="<td class='dhx_grid_dummy'></td></tr>"},e._grid._print_grid_header=function(a){for(var t="<div class='dhx_grid_line'>",n=e[a].columns,l=[],i=n.length,o=e._obj.clientWidth-2*n.length-20,r=0;r<n.length;r++){
var d=1*n[r].initialWidth;isNaN(d)||""===n[r].initialWidth||null===n[r].initialWidth||"boolean"==typeof n[r].initialWidth?l[r]=null:(i--,o-=d,l[r]=d)}for(var _=Math.floor(o/i),c=["text-align","padding-left","padding-right"],s=0;s<n.length;s++){var p=l[s]?l[s]:_;n[s].width=p-e._grid._calcPadding(n[s],a);var u=e._grid._getStyles(n[s],c);t+="<div style='width:"+(n[s].width-1)+"px;"+u.join(";")+"'>"+(void 0===n[s].label?n[s].id:n[s].label)+"</div>"}return t+="</div>"}});