/*
@license
dhtmlxScheduler.Net v.3.3.4 

This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Scheduler.plugin(function(e){e.config.limit_start=null,e.config.limit_end=null,e.config.limit_view=!1,e.config.check_limits=!0,e.config.mark_now=!0,e.config.display_marked_timespans=!0,e._temp_limit_scope=function(){function a(a,t,n,i,l){var r=e,o=[],d={_props:"map_to",matrix:"y_property"};for(var _ in d){var s=d[_];if(r[_])for(var c in r[_]){var p=r[_][c],u=p[s];a[u]&&(o=r._add_timespan_zones(o,e._get_blocked_zones(t[c],a[u],n,i,l)))}}return o=r._add_timespan_zones(o,e._get_blocked_zones(t,"global",n,i,l));

}var t=null,n="dhx_time_block",i="default",l=function(e,a,t){return a instanceof Date&&t instanceof Date?(e.start_date=a,e.end_date=t):(e.days=a,e.zones=t),e},r=function(e,a,t){var i="object"==typeof e?e:{days:e};return i.type=n,i.css="",a&&(t&&(i.sections=t),i=l(i,e,a)),i};e.blockTime=function(a,t,n){var i=r(a,t,n);return e.addMarkedTimespan(i)},e.unblockTime=function(a,t,n){t=t||"fullday";var i=r(a,t,n);return e.deleteMarkedTimespan(i)},e.attachEvent("onBeforeViewChange",function(a,t,n,i){function l(a,t){
var n=e.config.limit_start,i=e.config.limit_end,l=e.date.add(a,1,t);return a.valueOf()>i.valueOf()||l<=n.valueOf()}return e.config.limit_view&&(i=i||t,n=n||a,l(i,n)&&t.valueOf()!=i.valueOf())?(setTimeout(function(){var a=l(t,n)?e.config.limit_start:t;e.setCurrentView(l(a,n)?null:a,n)},1),!1):!0}),e.checkInMarkedTimespan=function(t,n,l){n=n||i;for(var r=!0,o=new Date(t.start_date.valueOf()),d=e.date.add(o,1,"day"),_=e._marked_timespans;o<t.end_date;o=e.date.date_part(d),d=e.date.add(o,1,"day")){var s=+e.date.date_part(new Date(o)),c=o.getDay(),p=a(t,_,c,s,n);

if(p)for(var u=0;u<p.length;u+=2){var v=e._get_zone_minutes(o),h=t.end_date>d||t.end_date.getDate()!=o.getDate()?1440:e._get_zone_minutes(t.end_date),b=p[u],m=p[u+1];if(h>b&&m>v&&(r="function"==typeof l?l(t,v,h,b,m):!1,!r))break}}return!r};var o=e.checkLimitViolation=function(a){if(!a)return!0;if(!e.config.check_limits)return!0;var t=e,i=t.config,l=[];if(a.rec_type)for(var r=e.getRecDates(a),o=0;o<r.length;o++){var d=e._copy_event(a);e._lame_copy(d,r[o]),l.push(d)}else l=[a];for(var _=!0,s=0;s<l.length;s++){
var c=!0,d=l[s];d._timed=e.isOneDayEvent(d),c=i.limit_start&&i.limit_end?d.start_date.valueOf()>=i.limit_start.valueOf()&&d.end_date.valueOf()<=i.limit_end.valueOf():!0,c&&(c=!e.checkInMarkedTimespan(d,n,function(e,a,n,i,l){var r=!0;return l>=a&&a>=i&&((1440==l||l>n)&&(r=!1),e._timed&&t._drag_id&&"new-size"==t._drag_mode?(e.start_date.setHours(0),e.start_date.setMinutes(l)):r=!1),(n>=i&&l>n||i>a&&n>l)&&(e._timed&&t._drag_id&&"new-size"==t._drag_mode?(e.end_date.setHours(0),e.end_date.setMinutes(i)):r=!1),
r})),c||(c=t.checkEvent("onLimitViolation")?t.callEvent("onLimitViolation",[d.id,d]):c),_=_&&c}return _||(t._drag_id=null,t._drag_mode=null),_};e._get_blocked_zones=function(e,a,t,n,i){var l=[];if(e&&e[a])for(var r=e[a],o=this._get_relevant_blocked_zones(t,n,r,i),d=0;d<o.length;d++)l=this._add_timespan_zones(l,o[d].zones);return l},e._get_relevant_blocked_zones=function(e,a,t,n){var i=t[a]&&t[a][n]?t[a][n]:t[e]&&t[e][n]?t[e][n]:[];return i},e.attachEvent("onMouseDown",function(e){return!(e==n)}),
e.attachEvent("onBeforeDrag",function(a){return a?o(e.getEvent(a)):!0}),e.attachEvent("onClick",function(a,t){return o(e.getEvent(a))}),e.attachEvent("onBeforeLightbox",function(a){var n=e.getEvent(a);return t=[n.start_date,n.end_date],o(n)}),e.attachEvent("onEventSave",function(a,t,n){if(!t.start_date||!t.end_date){var i=e.getEvent(a);t.start_date=new Date(i.start_date),t.end_date=new Date(i.end_date)}if(t.rec_type){var l=e._lame_clone(t);return e._roll_back_dates(l),o(l)}return o(t)}),e.attachEvent("onEventAdded",function(a){
if(!a)return!0;var t=e.getEvent(a);return!o(t)&&e.config.limit_start&&e.config.limit_end&&(t.start_date<e.config.limit_start&&(t.start_date=new Date(e.config.limit_start)),t.start_date.valueOf()>=e.config.limit_end.valueOf()&&(t.start_date=this.date.add(e.config.limit_end,-1,"day")),t.end_date<e.config.limit_start&&(t.end_date=new Date(e.config.limit_start)),t.end_date.valueOf()>=e.config.limit_end.valueOf()&&(t.end_date=this.date.add(e.config.limit_end,-1,"day")),t.start_date.valueOf()>=t.end_date.valueOf()&&(t.end_date=this.date.add(t.start_date,this.config.event_duration||this.config.time_step,"minute")),
t._timed=this.isOneDayEvent(t)),!0}),e.attachEvent("onEventChanged",function(a){if(!a)return!0;var n=e.getEvent(a);if(!o(n)){if(!t)return!1;n.start_date=t[0],n.end_date=t[1],n._timed=this.isOneDayEvent(n)}return!0}),e.attachEvent("onBeforeEventChanged",function(e,a,t){return o(e)}),e.attachEvent("onBeforeEventCreated",function(a){var t=e.getActionData(a).date,n={_timed:!0,start_date:t,end_date:e.date.add(t,e.config.time_step,"minute")};return o(n)}),e.attachEvent("onViewChange",function(){e._mark_now();

}),e.attachEvent("onSchedulerResize",function(){return window.setTimeout(function(){e._mark_now()},1),!0}),e.attachEvent("onTemplatesReady",function(){e._mark_now_timer=window.setInterval(function(){e._is_initialized()&&e._mark_now()},6e4)}),e._mark_now=function(a){var t="dhx_now_time";this._els[t]||(this._els[t]=[]);var n=e._currentDate(),i=this.config;if(e._remove_mark_now(),!a&&i.mark_now&&n<this._max_date&&n>this._min_date&&n.getHours()>=i.first_hour&&n.getHours()<i.last_hour){var l=this.locate_holder_day(n);

this._els[t]=e._append_mark_now(l,n)}},e._append_mark_now=function(a,t){var n="dhx_now_time",i=e._get_zone_minutes(t),l={zones:[i,i+1],css:n,type:n};if(!this._table_view){if(this._props&&this._props[this._mode]){for(var r=this._props[this._mode],o=r.size||r.options.length,d=a,_=a+o,s=(this._els.dhx_cal_data[0].childNodes,[]),c=d;_>c;c++){var p=c;l.days=p;var u=e._render_marked_timespan(l,null,p)[0];s.push(u)}return s}return l.days=a,e._render_marked_timespan(l,null,a)}return"month"==this._mode?(l.days=+e.date.date_part(t),
e._render_marked_timespan(l,null,null)):void 0},e._remove_mark_now=function(){for(var e="dhx_now_time",a=this._els[e],t=0;t<a.length;t++){var n=a[t],i=n.parentNode;i&&i.removeChild(n)}this._els[e]=[]},e._marked_timespans={global:{}},e._get_zone_minutes=function(e){return 60*e.getHours()+e.getMinutes()},e._prepare_timespan_options=function(a){var t=[],n=[];if("fullweek"==a.days&&(a.days=[0,1,2,3,4,5,6]),a.days instanceof Array){for(var l=a.days.slice(),r=0;r<l.length;r++){var o=e._lame_clone(a);o.days=l[r],
t.push.apply(t,e._prepare_timespan_options(o))}return t}if(!a||!(a.start_date&&a.end_date&&a.end_date>a.start_date||void 0!==a.days&&a.zones))return t;var d=0,_=1440;"fullday"==a.zones&&(a.zones=[d,_]),a.zones&&a.invert_zones&&(a.zones=e.invertZones(a.zones)),a.id=e.uid(),a.css=a.css||"",a.type=a.type||i;var s=a.sections;if(s){for(var c in s)if(s.hasOwnProperty(c)){var p=s[c];p instanceof Array||(p=[p]);for(var r=0;r<p.length;r++){var u=e._lame_copy({},a);u.sections={},u.sections[c]=p[r],n.push(u);

}}}else n.push(a);for(var v=0;v<n.length;v++){var h=n[v],b=h.start_date,m=h.end_date;if(b&&m)for(var y=e.date.date_part(new Date(b)),x=e.date.add(y,1,"day");m>y;){var u=e._lame_copy({},h);delete u.start_date,delete u.end_date,u.days=y.valueOf();var g=b>y?e._get_zone_minutes(b):d,f=m>x||m.getDate()!=y.getDate()?_:e._get_zone_minutes(m);u.zones=[g,f],t.push(u),y=x,x=e.date.add(x,1,"day")}else h.days instanceof Date&&(h.days=e.date.date_part(h.days).valueOf()),h.zones=a.zones.slice(),t.push(h)}return t;

},e._get_dates_by_index=function(a,t,n){var i=[];t=e.date.date_part(new Date(t||e._min_date)),n=new Date(n||e._max_date);for(var l=t.getDay(),r=a-l>=0?a-l:7-t.getDay()+a,o=e.date.add(t,r,"day");n>o;o=e.date.add(o,1,"week"))i.push(o);return i},e._get_css_classes_by_config=function(e){var a=[];return e.type==n&&(a.push(n),e.css&&a.push(n+"_reset")),a.push("dhx_marked_timespan",e.css),a.join(" ")},e._get_block_by_config=function(e){var a=document.createElement("DIV");return e.html&&("string"==typeof e.html?a.innerHTML=e.html:a.appendChild(e.html)),
a},e._render_marked_timespan=function(a,t,n){var i=[],l=e.config,r=this._min_date,o=this._max_date,d=!1;if(!l.display_marked_timespans)return i;if(!n&&0!==n){if(a.days<7)n=a.days;else{var _=new Date(a.days);if(d=+_,!(+o>+_&&+_>=+r))return i;n=_.getDay()}var s=r.getDay();s>n?n=7-(s-n):n-=s}var c=a.zones,p=e._get_css_classes_by_config(a);if(e._table_view&&"month"==e._mode){var u=[],v=[];if(t)u.push(t),v.push(n);else{v=d?[d]:e._get_dates_by_index(n);for(var h=0;h<v.length;h++)u.push(this._scales[v[h]]);

}for(var h=0;h<u.length;h++){t=u[h],n=v[h];var b=Math.floor((this._correct_shift(n,1)-r.valueOf())/(864e5*this._cols.length)),m=this.locate_holder_day(n,!1)%this._cols.length;if(!this._ignores[m]){var y=e._get_block_by_config(a),x=Math.max(t.offsetHeight-1,0),g=Math.max(t.offsetWidth-1,0),f=this._colsS[m],k=this._colsS.heights[b]+(this._colsS.height?this.xy.month_scale_height+2:2)-1;y.className=p,y.style.top=k+"px",y.style.lineHeight=y.style.height=x+"px";for(var w=0;w<c.length;w+=2){var D=c[h],S=c[h+1];

if(D>=S)return[];var M=y.cloneNode(!0);M.style.left=f+Math.round(D/1440*g)+"px",M.style.width=Math.round((S-D)/1440*g)+"px",t.appendChild(M),i.push(M)}}}}else{var E=n;if(this._ignores[this.locate_holder_day(n,!1)])return i;if(this._props&&this._props[this._mode]&&a.sections&&a.sections[this._mode]){var z=this._props[this._mode];E=z.order[a.sections[this._mode]];var A=z.order[a.sections[this._mode]];if(z.days>1){var O=z.size||z.options.length;E=E*O+A}else E=A,z.size&&E>z.position+z.size&&(E=0)}t=t?t:e.locate_holder(E);

for(var h=0;h<c.length;h+=2){var D=Math.max(c[h],60*l.first_hour),S=Math.min(c[h+1],60*l.last_hour);if(D>=S){if(h+2<c.length)continue;return[]}var M=e._get_block_by_config(a);M.className=p;var T=24*this.config.hour_size_px+1,J=36e5;M.style.top=Math.round((60*D*1e3-this.config.first_hour*J)*this.config.hour_size_px/J)%T+"px",M.style.lineHeight=M.style.height=Math.max(Math.round(60*(S-D)*1e3*this.config.hour_size_px/J)%T,1)+"px",t.appendChild(M),i.push(M)}}return i},e._mark_timespans=function(){for(var a=this._els.dhx_cal_data[0],t=[],n=new Date(e._min_date),i=0,l=a.childNodes.length;l>i;i++){
var r=a.childNodes[i];r.firstChild&&(r.firstChild.className||"").indexOf("dhx_scale_hour")>-1||(t.push.apply(t,e._on_scale_add_marker(r,n)),n=e.date.add(n,1,"day"))}return t},e.markTimespan=function(a){var t=!1;this._els.dhx_cal_data||(e.get_elements(),t=!0);var n=e._marked_timespans_ids,i=e._marked_timespans_types,l=e._marked_timespans;e.deleteMarkedTimespan(),e.addMarkedTimespan(a);var r=e._mark_timespans();return t&&(e._els=[]),e._marked_timespans_ids=n,e._marked_timespans_types=i,e._marked_timespans=l,
r},e.unmarkTimespan=function(e){if(e)for(var a=0;a<e.length;a++){var t=e[a];t.parentNode&&t.parentNode.removeChild(t)}},e._marked_timespans_ids={},e.addMarkedTimespan=function(a){var t=e._prepare_timespan_options(a),n="global";if(t.length){var i=t[0].id,l=e._marked_timespans,r=e._marked_timespans_ids;r[i]||(r[i]=[]);for(var o=0;o<t.length;o++){var d=t[o],_=d.days,s=(d.zones,d.css,d.sections),c=d.type;if(d.id=i,s){for(var p in s)if(s.hasOwnProperty(p)){l[p]||(l[p]={});var u=s[p],v=l[p];v[u]||(v[u]={}),
v[u][_]||(v[u][_]={}),v[u][_][c]||(v[u][_][c]=[],e._marked_timespans_types||(e._marked_timespans_types={}),e._marked_timespans_types[c]||(e._marked_timespans_types[c]=!0));var h=v[u][_][c];d._array=h,h.push(d),r[i].push(d)}}else{l[n][_]||(l[n][_]={}),l[n][_][c]||(l[n][_][c]=[]),e._marked_timespans_types||(e._marked_timespans_types={}),e._marked_timespans_types[c]||(e._marked_timespans_types[c]=!0);var h=l[n][_][c];d._array=h,h.push(d),r[i].push(d)}}return i}},e._add_timespan_zones=function(e,a){var t=e.slice();

if(a=a.slice(),!t.length)return a;for(var n=0;n<t.length;n+=2)for(var i=t[n],l=t[n+1],r=n+2==t.length,o=0;o<a.length;o+=2){var d=a[o],_=a[o+1];if(_>l&&l>=d||i>d&&_>=i)t[n]=Math.min(i,d),t[n+1]=Math.max(l,_),n-=2;else{if(!r)continue;var s=i>d?0:2;t.splice(n+s,0,d,_)}a.splice(o--,2);break}return t},e._subtract_timespan_zones=function(e,a){for(var t=e.slice(),n=0;n<t.length;n+=2)for(var i=t[n],l=t[n+1],r=0;r<a.length;r+=2){var o=a[r],d=a[r+1];if(d>i&&l>o){var _=!1;i>=o&&d>=l&&t.splice(n,2),o>i&&(t.splice(n,2,i,o),
_=!0),l>d&&t.splice(_?n+2:n,_?0:2,d,l),n-=2;break}}return t},e.invertZones=function(a){return e._subtract_timespan_zones([0,1440],a.slice())},e._delete_marked_timespan_by_id=function(a){var t=e._marked_timespans_ids[a];if(t)for(var n=0;n<t.length;n++)for(var i=t[n],l=i._array,r=0;r<l.length;r++)if(l[r]==i){l.splice(r,1);break}},e._delete_marked_timespan_by_config=function(a){var t=e._marked_timespans,n=a.sections,l=a.days,r=a.type||i,o=[];if(n){for(var d in n)if(n.hasOwnProperty(d)&&t[d]){var _=n[d];

t[d][_]&&t[d][_][l]&&t[d][_][l][r]&&(o=t[d][_][l][r])}}else t.global[l]&&t.global[l][r]&&(o=t.global[l][r]);for(var s=0;s<o.length;s++){var c=o[s],p=e._subtract_timespan_zones(c.zones,a.zones);if(p.length)c.zones=p;else{o.splice(s,1),s--;for(var u=e._marked_timespans_ids[c.id],v=0;v<u.length;v++)if(u[v]==c){u.splice(v,1);break}}}for(var s in e._marked_timespans.timeline)for(var h in e._marked_timespans.timeline[s])for(var v in e._marked_timespans.timeline[s][h])v===r&&delete e._marked_timespans.timeline[s][h][v];

},e.deleteMarkedTimespan=function(a){if(arguments.length||(e._marked_timespans={global:{}},e._marked_timespans_ids={},e._marked_timespans_types={}),"object"!=typeof a)e._delete_marked_timespan_by_id(a);else{a.start_date&&a.end_date||(a.days||(a.days="fullweek"),a.zones||(a.zones="fullday"));var t=[];if(a.type)t.push(a.type);else for(var n in e._marked_timespans_types)t.push(n);for(var i=e._prepare_timespan_options(a),l=0;l<i.length;l++)for(var r=i[l],o=0;o<t.length;o++){var d=e._lame_clone(r);d.type=t[o],
e._delete_marked_timespan_by_config(d)}}},e._get_types_to_render=function(e,a){var t=e?e:{};for(var n in a||{})a.hasOwnProperty(n)&&(t[n]=a[n]);return t},e._get_configs_to_render=function(e){var a=[];for(var t in e)e.hasOwnProperty(t)&&a.push.apply(a,e[t]);return a},e._on_scale_add_marker=function(a,t){if(!e._table_view||"month"==e._mode){var n=t.getDay(),i=t.valueOf(),l=this._mode,r=e._marked_timespans,o=[],d=[];if(this._props&&this._props[l]){var _=this._props[l],s=_.options,c=e._get_unit_index(_,t),p=s[c];

if(_.days>1){var u=864e5,v=Math.floor((t-e._min_date)/u);t=e.date.add(e._min_date,Math.floor(v/s.length),"day"),t=e.date.date_part(t)}else t=e.date.date_part(new Date(this._date));if(n=t.getDay(),i=t.valueOf(),r[l]&&r[l][p.key]){var h=r[l][p.key],b=e._get_types_to_render(h[n],h[i]);o.push.apply(o,e._get_configs_to_render(b))}}var m=r.global,y=m[i]||m[n];o.push.apply(o,e._get_configs_to_render(y));for(var x=0;x<o.length;x++)d.push.apply(d,e._render_marked_timespan(o[x],a,t));return d}},e.attachEvent("onScaleAdd",function(){
e._on_scale_add_marker.apply(e,arguments)}),e.dblclick_dhx_marked_timespan=function(a,t){e.config.dblclick_create||e.callEvent("onScaleDblClick",[e.getActionData(a).date,t,a]),e.addEventNow(e.getActionData(a).date,null,a)}},e._temp_limit_scope()});