/*
@license
dhtmlxScheduler.Net v.3.3.4 

This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Scheduler.plugin(function(e){!function(){function t(e){return e.replace(w,"\n").replace(k,"")}function a(e,t){e=parseFloat(e),t=parseFloat(t),isNaN(t)||(e-=t);var a=i(e);return e=e-a.width+a.cols*x,isNaN(e)?"auto":100*e/x}function n(e,t,a){e=parseFloat(e),t=parseFloat(t),!isNaN(t)&&a&&(e-=t);var n=i(e);return e=e-n.width+n.cols*x,isNaN(e)?"auto":100*e/(x-(isNaN(t)?0:t))}function i(t){for(var a=0,n=e._els.dhx_cal_header[0].childNodes,i=n[1]?n[1].childNodes:n[0].childNodes,l=0;l<i.length;l++){var r=i[l].style?i[l]:i[l].parentNode,o=parseFloat(r.style.width);

if(!(t>o))break;t-=o+1,a+=o+1}return{width:a,cols:l}}function l(e){return e=parseFloat(e),isNaN(e)?"auto":100*e/f}function r(e,t){return(window.getComputedStyle?window.getComputedStyle(e,null)[t]:e.currentStyle?e.currentStyle[t]:null)||""}function o(t,a){for(var n=parseInt(t.style.left,10),i=0;i<e._cols.length;i++)if(n-=e._cols[i],0>n)return i;return a}function d(t,a){for(var n=parseInt(t.style.top,10),i=0;i<e._colsS.heights.length;i++)if(e._colsS.heights[i]>n)return i;return a}function _(e){return e?"<"+e+">":"";

}function s(e){return e?"</"+e+">":""}function c(e,t,a,n){var i="<"+e+" profile='"+t+"'";return a&&(i+=" header='"+a+"'"),n&&(i+=" footer='"+n+"'"),i+=">"}function u(){var a="",n=e._mode;if(e.matrix&&e.matrix[e._mode]&&(n="cell"==e.matrix[e._mode].render?"matrix":"timeline"),a+="<scale mode='"+n+"' today='"+e._els.dhx_cal_date[0].innerHTML+"'>","week_agenda"==e._mode)for(var i=e._els.dhx_cal_data[0].getElementsByTagName("DIV"),l=0;l<i.length;l++)"dhx_wa_scale_bar"==i[l].className&&(a+="<column>"+t(i[l].innerHTML)+"</column>");
else if("agenda"==e._mode||"map"==e._mode){var i=e._els.dhx_cal_header[0].childNodes[0].childNodes;a+="<column>"+t(i[0].innerHTML)+"</column><column>"+t(i[1].innerHTML)+"</column>"}else if("year"==e._mode)for(var i=e._els.dhx_cal_data[0].childNodes,l=0;l<i.length;l++)a+="<month label='"+t(i[l].childNodes[0].innerHTML)+"'>",a+=v(i[l].childNodes[1].childNodes),a+=p(i[l].childNodes[2]),a+="</month>";else{a+="<x>";var i=e._els.dhx_cal_header[0].childNodes;a+=v(i),a+="</x>";var r=e._els.dhx_cal_data[0];

if(e.matrix&&e.matrix[e._mode]){a+="<y>";for(var l=0;l<r.firstChild.rows.length;l++){var o=r.firstChild.rows[l];a+="<row><![CDATA["+t(o.cells[0].innerHTML)+"]]></row>"}a+="</y>",f=r.firstChild.rows[0].cells[0].offsetHeight}else if("TABLE"==r.firstChild.tagName)a+=p(r);else{for(r=r.childNodes[r.childNodes.length-1];-1==r.className.indexOf("dhx_scale_holder");)r=r.previousSibling;r=r.childNodes,a+="<y>";for(var l=0;l<r.length;l++)a+="\n<row><![CDATA["+t(r[l].innerHTML)+"]]></row>";a+="</y>",f=r[0].offsetHeight;

}}return a+="</scale>"}function p(e){for(var a="",n=e.firstChild.rows,i=0;i<n.length;i++){for(var l=[],r=0;r<n[i].cells.length;r++)l.push(n[i].cells[r].firstChild.innerHTML);a+="\n<row height='"+e.firstChild.rows[i].cells[0].offsetHeight+"'><![CDATA["+t(l.join("|"))+"]]></row>",f=e.firstChild.rows[0].cells[0].offsetHeight}return a}function v(a){var n,i="";e.matrix&&e.matrix[e._mode]&&(e.matrix[e._mode].second_scale&&(n=a[1].childNodes),a=a[0].childNodes);for(var l=0;l<a.length;l++)i+="\n<column><![CDATA["+t(a[l].innerHTML)+"]]></column>";

if(x=a[0].offsetWidth,n)for(var r=0,o=a[0].offsetWidth,d=1,l=0;l<n.length;l++)i+="\n<column second_scale='"+d+"'><![CDATA["+t(n[l].innerHTML)+"]]></column>",r+=n[l].offsetWidth,r>=o&&(o+=a[d]?a[d].offsetWidth:0,d++),x=n[0].offsetWidth;return i}function h(i){var _="",s=e._rendered,c=e.matrix&&e.matrix[e._mode];if("agenda"==e._mode||"map"==e._mode)for(var u=0;u<s.length;u++)_+="<event><head><![CDATA["+t(s[u].childNodes[0].innerHTML)+"]]></head><body><![CDATA["+t(s[u].childNodes[2].innerHTML)+"]]></body></event>";
else if("week_agenda"==e._mode)for(var u=0;u<s.length;u++)_+="<event day='"+s[u].parentNode.getAttribute("day")+"'><body>"+t(s[u].innerHTML)+"</body></event>";else if("year"==e._mode)for(var s=e.get_visible_events(),u=0;u<s.length;u++){var p=s[u].start_date;for(p.valueOf()<e._min_date.valueOf()&&(p=e._min_date);p<s[u].end_date;){var v=p.getMonth()+12*(p.getFullYear()-e._min_date.getFullYear())-e.week_starts._month,h=e.week_starts[v]+p.getDate()-1,m=i?r(e._get_year_cell(p),"color"):"",b=i?r(e._get_year_cell(p),"backgroundColor"):"";

if(_+="<event day='"+h%7+"' week='"+Math.floor(h/7)+"' month='"+v+"' backgroundColor='"+b+"' color='"+m+"'></event>",p=e.date.add(p,1,"day"),p.valueOf()>=e._max_date.valueOf())break}}else if(c&&"cell"==c.render)for(var s=e._els.dhx_cal_data[0].getElementsByTagName("TD"),u=0;u<s.length;u++){var m=i?r(s[u],"color"):"",b=i?r(s[u],"backgroundColor"):"";_+="\n<event><body backgroundColor='"+b+"' color='"+m+"'><![CDATA["+t(s[u].innerHTML)+"]]></body></event>"}else for(var u=0;u<s.length;u++){var y,g;if(e.matrix&&e.matrix[e._mode])y=a(s[u].style.left),
g=a(s[u].offsetWidth)-1;else{var x=e.config.use_select_menu_space?0:26;y=n(s[u].style.left,x,!0),g=n(s[u].style.width,x)-1}if(!isNaN(1*g)){var k=l(s[u].style.top),w=l(s[u].style.height),D=s[u].className.split(" ")[0].replace("dhx_cal_","");if("dhx_tooltip_line"!==D){var E=e.getEvent(s[u].getAttribute("event_id"));if(E){var h=E._sday,M=E._sweek,S=E._length||0;if("month"==e._mode)w=parseInt(s[u].offsetHeight,10),k=parseInt(s[u].style.top,10)-e.xy.month_head_height,h=o(s[u],h),M=d(s[u],M);else if(e.matrix&&e.matrix[e._mode]){
h=0;var N=s[u].parentNode.parentNode.parentNode;M=N.rowIndex;var C=f;f=s[u].parentNode.offsetHeight,k=l(s[u].style.top),k-=.2*k,f=C}else{if(s[u].parentNode==e._els.dhx_cal_data[0])continue;var z=e._els.dhx_cal_data[0].childNodes[0],T=parseFloat(-1!=z.className.indexOf("dhx_scale_holder")?z.style.left:0);y+=a(s[u].parentNode.style.left,T)}if(_+="\n<event week='"+M+"' day='"+h+"' type='"+D+"' x='"+y+"' y='"+k+"' width='"+g+"' height='"+w+"' len='"+S+"'>","event"==D){_+="<header><![CDATA["+t(s[u].childNodes[1].innerHTML)+"]]></header>";

var m=i?r(s[u].childNodes[2],"color"):"",b=i?r(s[u].childNodes[2],"backgroundColor"):"";_+="<body backgroundColor='"+b+"' color='"+m+"'><![CDATA["+t(s[u].childNodes[2].innerHTML)+"]]></body>"}else{var m=i?r(s[u],"color"):"",b=i?r(s[u],"backgroundColor"):"";_+="<body backgroundColor='"+b+"' color='"+m+"'><![CDATA["+t(s[u].innerHTML)+"]]></body>"}_+="</event>"}}}}return _}function m(t,a,n,i,l,r){var o=!1;"fullcolor"==i&&(o=!0,i="color"),i=i||"color";var d="";if(t){var p=e._date,v=e._mode;a=e.date[n+"_start"](a),
a=e.date["get_"+n+"_end"]?e.date["get_"+n+"_end"](a):e.date.add(a,1,n),d=c("pages",i,l,r);for(var m=new Date(t);+a>+m;m=this.date.add(m,1,n))this.setCurrentView(m,n),d+=_("page")+u().replace("–","-")+h(o)+s("page");d+=s("pages"),this.setCurrentView(p,v)}else d=c("data",i,l,r)+u().replace("–","-")+h(o)+s("data");return d}function b(t,a){var n=e.uid(),i=document.createElement("div");i.style.display="none",document.body.appendChild(i),i.innerHTML='<form id="'+n+'" method="post" target="_blank" action="'+a+'" accept-charset="utf-8" enctype="application/x-www-form-urlencoded"><input type="hidden" name="mycoolxmlbody"/> </form>',
document.getElementById(n).firstChild.value=encodeURIComponent(t),document.getElementById(n).submit(),i.parentNode.removeChild(i)}function y(e,t,a,n,i,l,r){var o="";o="object"==typeof i?g(i):m.apply(this,[e,t,a,i,l,r]),b(o,n)}function g(e){for(var t="<data>",a=0;a<e.length;a++)t+=e[a].source.getPDFData(e[a].start,e[a].end,e[a].view,e[a].mode,e[a].header,e[a].footer);return t+="</data>"}var x,f,k=new RegExp("<[^>]*>","g"),w=new RegExp("<br[^>]*>","g");e.getPDFData=m,e.toPDF=function(e,t,a,n){return y.apply(this,[null,null,null,e,t,a,n]);

},e.toPDFRange=function(t,a,n,i,l,r,o){return"string"==typeof t&&(t=e.templates.api_date(t),a=e.templates.api_date(a)),y.apply(this,arguments)}}()});