/*
@license
dhtmlxScheduler.Net v.3.3.4 

This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Scheduler.plugin(function(e){e.attachEvent("onTemplatesReady",function(){this.layers.sort(function(e,a){return e.zIndex-a.zIndex}),e._dp_init=function(a){a._methods=["_set_event_text_style","","changeEventId","deleteEvent"],this.attachEvent("onEventAdded",function(e){!this._loading&&this.validId(e)&&this.getEvent(e)&&this.getEvent(e).layer==a.layer&&a.setUpdated(e,!0,"inserted")}),this.attachEvent("onBeforeEventDelete",function(e){if(this.getEvent(e)&&this.getEvent(e).layer==a.layer){if(!this.validId(e))return;

var t=a.getState(e);return"inserted"==t||this._new_event?(a.setUpdated(e,!1),!0):"deleted"==t?!1:"true_deleted"==t?!0:(a.setUpdated(e,!0,"deleted"),!1)}return!0}),this.attachEvent("onEventChanged",function(e){!this._loading&&this.validId(e)&&this.getEvent(e)&&this.getEvent(e).layer==a.layer&&a.setUpdated(e,!0,"updated")}),a._getRowData=function(e,a){var t=this.obj.getEvent(e),n={};for(var l in t)0!==l.indexOf("_")&&(n[l]=t[l]&&t[l].getUTCFullYear?this.obj.templates.xml_format(t[l]):t[l]);return n;

},a._clearUpdateFlag=function(){},a.attachEvent("insertCallback",e._update_callback),a.attachEvent("updateCallback",e._update_callback),a.attachEvent("deleteCallback",function(e,a){this.obj.setUserData(a,this.action_param,"true_deleted"),this.obj.deleteEvent(a)})},function(){var a=function(e){if(null===e||"object"!=typeof e)return e;var t=new e.constructor;for(var n in e)t[n]=a(e[n]);return t};e._dataprocessors=[],e._layers_zindex={};for(var t=0;t<e.layers.length;t++){if(e.config["lightbox_"+e.layers[t].name]={},
e.config["lightbox_"+e.layers[t].name].sections=a(e.config.lightbox.sections),e._layers_zindex[e.layers[t].name]=e.config.inital_layer_zindex||5+3*t,e.layers[t].url){var n=new dataProcessor(e.layers[t].url);n.layer=e.layers[t].name,e._dataprocessors.push(n),e._dataprocessors[t].init(e)}e.layers[t].isDefault&&(e.defaultLayer=e.layers[t].name)}}(),e.showLayer=function(e){this.toggleLayer(e,!0)},e.hideLayer=function(e){this.toggleLayer(e,!1)},e.toggleLayer=function(e,a){var t=this.getLayer(e);t.visible="undefined"!=typeof a?!!a:!t.visible,
this.setCurrentView(this._date,this._mode)},e.getLayer=function(a){var t,n;"string"==typeof a&&(n=a),"object"==typeof a&&(n=a.layer);for(var l=0;l<e.layers.length;l++)e.layers[l].name==n&&(t=e.layers[l]);return t},e.attachEvent("onBeforeLightbox",function(a){var t=this.getEvent(a);return this.config.lightbox.sections=this.config["lightbox_"+t.layer].sections,e.resetLightbox(),!0}),e.attachEvent("onClick",function(a,t){var n=e.getEvent(a);return!e.getLayer(n.layer).noMenu}),e.attachEvent("onEventCollision",function(a,t){
var n=this.getLayer(a);if(!n.checkCollision)return!1;for(var l=0,i=0;i<t.length;i++)t[i].layer==n.name&&t[i].id!=a.id&&l++;return l>=e.config.collision_limit}),e.addEvent=function(a,t,n,l,i){var r=a;1!=arguments.length&&(r=i||{},r.start_date=a,r.end_date=t,r.text=n,r.id=l,r.layer=this.defaultLayer),r.id=r.id||e.uid(),r.text=r.text||"","string"==typeof r.start_date&&(r.start_date=this.templates.api_date(r.start_date)),"string"==typeof r.end_date&&(r.end_date=this.templates.api_date(r.end_date)),r._timed=this.isOneDayEvent(r);

var o=!this._events[r.id];this._events[r.id]=r,this.event_updated(r),this._loading||this.callEvent(o?"onEventAdded":"onEventChanged",[r.id,r])},this._evs_layer={};for(var a=0;a<this.layers.length;a++)this._evs_layer[this.layers[a].name]=[];e.addEventNow=function(a,t,n){var l={};"object"==typeof a&&(l=a,a=null);var i=6e4*(this.config.event_duration||this.config.time_step);a||(a=Math.round(e._currentDate().valueOf()/i)*i);var r=new Date(a);if(!t){var o=this.config.first_hour;o>r.getHours()&&(r.setHours(o),
a=r.valueOf()),t=a+i}l.start_date=l.start_date||r,l.end_date=l.end_date||new Date(t),l.text=l.text||this.locale.labels.new_event,l.id=this._drag_id=this.uid(),l.layer=this.defaultLayer,this._drag_mode="new-size",this._loading=!0,this.addEvent(l),this.callEvent("onEventCreated",[this._drag_id,n]),this._loading=!1,this._drag_event={},this._on_mouse_up(n)},e._t_render_view_data=function(e){if(this.config.multi_day&&!this._table_view){for(var a=[],t=[],n=0;n<e.length;n++)e[n]._timed?a.push(e[n]):t.push(e[n]);

this._table_view=!0,this.render_data(t),this._table_view=!1,this.render_data(a)}else this.render_data(e)},e.render_view_data=function(){if(this._not_render)return void(this._render_wait=!0);this._render_wait=!1,this.clear_view(),this._evs_layer={};for(var e=0;e<this.layers.length;e++)this._evs_layer[this.layers[e].name]=[];for(var a=this.get_visible_events(),e=0;e<a.length;e++)this._evs_layer[a[e].layer]&&this._evs_layer[a[e].layer].push(a[e]);if("month"==this._mode){for(var t=[],e=0;e<this.layers.length;e++)this.layers[e].visible&&(t=t.concat(this._evs_layer[this.layers[e].name]));

this._t_render_view_data(t)}else for(var e=0;e<this.layers.length;e++)if(this.layers[e].visible){var n=this._evs_layer[this.layers[e].name];this._t_render_view_data(n)}},e._render_v_bar=function(a,t,n,l,i,r,o,d,_){var s=a.id;-1==o.indexOf("<div class=")&&(o=e.templates["event_header_"+a.layer]?e.templates["event_header_"+a.layer](a.start_date,a.end_date,a):o),-1==d.indexOf("<div class=")&&(d=e.templates["event_text_"+a.layer]?e.templates["event_text_"+a.layer](a.start_date,a.end_date,a):d);var c=document.createElement("DIV"),p="dhx_cal_event",u=e.templates["event_class_"+a.layer]?e.templates["event_class_"+a.layer](a.start_date,a.end_date,a):e.templates.event_class(a.start_date,a.end_date,a);

u&&(p=p+" "+u);var v='<div event_id="'+s+'" class="'+p+'" style="position:absolute; top:'+n+"px; left:"+t+"px; width:"+(l-4)+"px; height:"+i+"px;"+(r||"")+'">';return v+='<div class="dhx_header" style=" width:'+(l-6)+'px;" >&nbsp;</div>',v+='<div class="dhx_title">'+o+"</div>",v+='<div class="dhx_body" style=" width:'+(l-(this._quirks?4:14))+"px; height:"+(i-(this._quirks?20:30))+'px;">'+d+"</div>",v+='<div class="dhx_footer" style=" width:'+(l-8)+"px;"+(_?" margin-top:-1px;":"")+'" ></div></div>',
c.innerHTML=v,c.style.zIndex=100,c.firstChild},e.render_event_bar=function(a){var t=this._els.dhx_cal_data[0],n=this._colsS[a._sday],l=this._colsS[a._eday];l==n&&(l=this._colsS[a._eday+1]);var i=this.xy.bar_height,r=this._colsS.heights[a._sweek]+(this._colsS.height?this.xy.month_scale_height+2:2)+a._sorder*i,o=document.createElement("DIV"),d=a._timed?"dhx_cal_event_clear":"dhx_cal_event_line",_=e.templates["event_class_"+a.layer]?e.templates["event_class_"+a.layer](a.start_date,a.end_date,a):e.templates.event_class(a.start_date,a.end_date,a);

_&&(d=d+" "+_);var s='<div event_id="'+a.id+'" class="'+d+'" style="position:absolute; top:'+r+"px; left:"+n+"px; width:"+(l-n-15)+"px;"+(a._text_style||"")+'">';a._timed&&(s+=e.templates["event_bar_date_"+a.layer]?e.templates["event_bar_date_"+a.layer](a.start_date,a.end_date,a):e.templates.event_bar_date(a.start_date,a.end_date,a)),s+=e.templates["event_bar_text_"+a.layer]?e.templates["event_bar_text_"+a.layer](a.start_date,a.end_date,a):e.templates.event_bar_text(a.start_date,a.end_date,a)+"</div>)",
s+="</div>",o.innerHTML=s,this._rendered.push(o.firstChild),t.appendChild(o.firstChild)},e.render_event=function(a){var t=e.xy.menu_width;if(e.getLayer(a.layer).noMenu&&(t=0),!(a._sday<0)){var n=e.locate_holder(a._sday);if(n){var l=60*a.start_date.getHours()+a.start_date.getMinutes(),i=60*a.end_date.getHours()+a.end_date.getMinutes()||60*e.config.last_hour,r=Math.round((60*l*1e3-60*this.config.first_hour*60*1e3)*this.config.hour_size_px/36e5)%(24*this.config.hour_size_px)+1,o=Math.max(e.xy.min_event_height,(i-l)*this.config.hour_size_px/60)+1,d=Math.floor((n.clientWidth-t)/a._count),_=a._sorder*d+1;

a._inner||(d*=a._count-a._sorder);var s=this._render_v_bar(a.id,t+_,r,d,o,a._text_style,e.templates.event_header(a.start_date,a.end_date,a),e.templates.event_text(a.start_date,a.end_date,a));if(this._rendered.push(s),n.appendChild(s),_=_+parseInt(n.style.left,10)+t,r+=this._dy_shift,s.style.zIndex=this._layers_zindex[a.layer],this._edit_id==a.id){s.style.zIndex=parseInt(s.style.zIndex)+1;var c=s.style.zIndex;d=Math.max(d-4,e.xy.editor_width);var s=document.createElement("DIV");s.setAttribute("event_id",a.id),
this.set_xy(s,d,o-20,_,r+14),s.className="dhx_cal_editor",s.style.zIndex=c;var p=document.createElement("DIV");this.set_xy(p,d-6,o-26),p.style.cssText+=";margin:2px 2px 2px 2px;overflow:hidden;",p.style.zIndex=c,s.appendChild(p),this._els.dhx_cal_data[0].appendChild(s),this._rendered.push(s),p.innerHTML="<textarea class='dhx_cal_editor'>"+a.text+"</textarea>",this._quirks7&&(p.firstChild.style.height=o-12+"px"),this._editor=p.firstChild,this._editor.onkeypress=function(a){if((a||event).shiftKey)return!0;

var t=(a||event).keyCode;t==e.keys.edit_save&&e.editStop(!0),t==e.keys.edit_cancel&&e.editStop(!1)},this._editor.onselectstart=function(e){return(e||event).cancelBubble=!0,!0},p.firstChild.focus(),this._els.dhx_cal_data[0].scrollLeft=0,p.firstChild.select()}if(this._select_id==a.id){s.style.zIndex=parseInt(s.style.zIndex)+1;for(var u=this.config["icons_"+(this._edit_id==a.id?"edit":"select")],v="",h=0;h<u.length;h++)v+="<div class='dhx_menu_icon "+u[h]+"' title='"+this.locale.labels[u[h]]+"'></div>";

var b=this._render_v_bar(a.id,_-t+1,r,t,20*u.length+26,"","<div class='dhx_menu_head'></div>",v,!0);b.style.left=_-t+1,b.style.zIndex=s.style.zIndex,this._els.dhx_cal_data[0].appendChild(b),this._rendered.push(b)}}}},e.filter_agenda=function(a,t){var n=e.getLayer(t.layer);return n&&n.visible}})});