/*
@license
dhtmlxScheduler.Net v.3.3.4 

This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Scheduler.plugin(function(e){e.config.multisection=!0,e.config.multisection_shift_all=!0,e.config.section_delimiter=",",e.attachEvent("onSchedulerReady",function(){e._register_copies_array=function(e){for(var t=0;t<e.length;t++)this._register_copy(e[t])},e._register_copy=function(e){this._multisection_copies[e.id]||(this._multisection_copies[e.id]={});var t=e[this._get_section_property()],a=this._multisection_copies[e.id];a[t]||(a[t]=e)},e._get_copied_event=function(t,a){if(!this._multisection_copies[t])return null;

if(this._multisection_copies[t][a])return this._multisection_copies[t][a];var n=this._multisection_copies[t];if(e._drag_event&&e._drag_event._orig_section&&n[e._drag_event._orig_section])return n[e._drag_event._orig_section];var i=1/0,l=null;for(var r in n)n[r]._sorder<i&&(l=n[r],i=n[r]._sorder);return l},e._clear_copied_events=function(){this._multisection_copies={}},e._restore_render_flags=function(t){for(var a=this._get_section_property(),n=0;n<t.length;n++){var i=t[n],l=e._get_copied_event(i.id,i[a]);

if(l)for(var r in l)0===r.indexOf("_")&&(i[r]=l[r])}};var t=e._update_unit_section;e._update_unit_section=function(a){return e._update_sections(a,t)};var a=e._update_timeline_section;e._update_timeline_section=function(t){return e._update_sections(t,a)},e.isMultisectionEvent=function(e){if(e&&this._get_multisection_view()){var t=this._get_event_sections(e);return t.length>1}return!1},e._get_event_sections=function(e){var t=this._get_section_property(),a=e[t]||"";return this._parse_event_sections(a);

},e._parse_event_sections=function(t){return t instanceof Array?t:t.toString().split(e.config.section_delimiter)},e._clear_copied_events(),e._split_events=function(t){var a=[],n=this._get_multisection_view(),i=this._get_section_property();if(n)for(var l=0;l<t.length;l++){var r=this._get_event_sections(t[l]);if(r.length>1){for(var o=0;o<r.length;o++)if("undefined"!=typeof n.order[r[o]]){var d=e._copy_event(t[l]);d[i]=r[o],a.push(d)}}else a.push(t[l])}else a=t;return a},e._get_multisection_view=function(){
return this.config.multisection?e._get_section_view():!1};var n=e.get_visible_events;e.get_visible_events=function(e){this._clear_copied_events();var t=n.apply(this,arguments);if(this._get_multisection_view()){t=this._split_events(t);for(var a=0;a<t.length;a++)this.is_visible_events(t[a])||(t.splice(a,1),a--);this._register_copies_array(t)}return t},e._rendered_events={};var i=e.render_view_data;e.render_view_data=function(e,t){return this._get_multisection_view()&&e&&(e=this._split_events(e),this._restore_render_flags(e)),
i.apply(this,[e,t])},e._update_sections=function(t,a){var n=t.view,i=t.event,l=t.pos;if(e.isMultisectionEvent(i)){if(e._drag_event._orig_section||(e._drag_event._orig_section=l.section),e._drag_event._orig_section!=l.section){var r=n.order[l.section]-n.order[e._drag_event._orig_section];if(r){var o=this._get_event_sections(i),d=[],_=!0;if(e.config.multisection_shift_all)for(var s=0;s<o.length;s++){var c=e._shift_sections(n,o[s],r);if(null===c){d=o,_=!1;break}d[s]=c}else for(var s=0;s<o.length;s++){
if(o[s]==l.section){d=o,_=!1;break}if(o[s]==e._drag_event._orig_section){var c=e._shift_sections(n,o[s],r);if(null===c){d=o,_=!1;break}d[s]=c}else d[s]=o[s]}_&&(e._drag_event._orig_section=l.section),i[e._get_section_property()]=d.join(e.config.section_delimiter)}}}else a.apply(e,[t])},e._shift_sections=function(e,t,a){for(var n=null,i=e.y_unit||e.options,l=0;l<i.length;l++)if(i[l].key==t){n=l;break}var r=i[n+a];return r?r.key:null};var l=e._get_blocked_zones;e._get_blocked_zones=function(e,t,a,n,i){
if(t&&this.config.multisection){t=this._parse_event_sections(t);for(var r=[],o=0;o<t.length;o++)r=r.concat(l.apply(this,[e,t[o],a,n,i]));return r}return l.apply(this,arguments)};var r=e._check_sections_collision;e._check_sections_collision=function(e,t){if(this.config.multisection&&this._get_section_view()){e=this._split_events([e]),t=this._split_events([t]);for(var a=!1,n=0,i=e.length;i>n&&!a;n++)for(var l=0,o=t.length;o>l;l++)if(r.apply(this,[e[n],t[l]])){a=!0;break}return a}return r.apply(this,arguments);

}})});