//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PepuxFront.IpServiceLink {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActiveConfs", Namespace="http://schemas.datacontract.org/2004/07/PepuxService")]
    [System.SerializableAttribute()]
    public partial class ActiveConfs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_lockedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resource_uriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string service_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string start_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string start_time2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lock_pathField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_locked {
            get {
                return this.is_lockedField;
            }
            set {
                if ((this.is_lockedField.Equals(value) != true)) {
                    this.is_lockedField = value;
                    this.RaisePropertyChanged("is_locked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resource_uri {
            get {
                return this.resource_uriField;
            }
            set {
                if ((object.ReferenceEquals(this.resource_uriField, value) != true)) {
                    this.resource_uriField = value;
                    this.RaisePropertyChanged("resource_uri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string service_type {
            get {
                return this.service_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.service_typeField, value) != true)) {
                    this.service_typeField = value;
                    this.RaisePropertyChanged("service_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string start_time {
            get {
                return this.start_timeField;
            }
            set {
                if ((object.ReferenceEquals(this.start_timeField, value) != true)) {
                    this.start_timeField = value;
                    this.RaisePropertyChanged("start_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string start_time2 {
            get {
                return this.start_time2Field;
            }
            set {
                if ((object.ReferenceEquals(this.start_time2Field, value) != true)) {
                    this.start_time2Field = value;
                    this.RaisePropertyChanged("start_time2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tag {
            get {
                return this.tagField;
            }
            set {
                if ((object.ReferenceEquals(this.tagField, value) != true)) {
                    this.tagField = value;
                    this.RaisePropertyChanged("tag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string lock_path {
            get {
                return this.lock_pathField;
            }
            set {
                if ((object.ReferenceEquals(this.lock_pathField, value) != true)) {
                    this.lock_pathField = value;
                    this.RaisePropertyChanged("lock_path");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Service", Namespace="http://schemas.datacontract.org/2004/07/PepuxService")]
    [System.SerializableAttribute()]
    public partial class Service : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PepuxFront.IpServiceLink.Phonebook[] PhonebooksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdName {
            get {
                return this.AdNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AdNameField, value) != true)) {
                    this.AdNameField = value;
                    this.RaisePropertyChanged("AdName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PepuxFront.IpServiceLink.Phonebook[] Phonebooks {
            get {
                return this.PhonebooksField;
            }
            set {
                if ((object.ReferenceEquals(this.PhonebooksField, value) != true)) {
                    this.PhonebooksField = value;
                    this.RaisePropertyChanged("Phonebooks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Phonebook", Namespace="http://schemas.datacontract.org/2004/07/PepuxService")]
    [System.SerializableAttribute()]
    public partial class Phonebook : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PepuxFront.IpServiceLink.Service ServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VMRiDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PepuxFront.IpServiceLink.Service Service {
            get {
                return this.ServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceField, value) != true)) {
                    this.ServiceField = value;
                    this.RaisePropertyChanged("Service");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> VMRiD {
            get {
                return this.VMRiDField;
            }
            set {
                if ((this.VMRiDField.Equals(value) != true)) {
                    this.VMRiDField = value;
                    this.RaisePropertyChanged("VMRiD");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="participants", Namespace="http://schemas.datacontract.org/2004/07/PepuxService")]
    [System.SerializableAttribute()]
    public partial class participants : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int bandwidthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string call_directionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string call_uuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string conferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string connect_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string destination_aliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string display_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string encryptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool has_mediaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_mutedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_on_holdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_presentation_supportedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_presentingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_streamingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int license_countField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string media_nodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parent_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string participant_aliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string protocolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string remote_addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int remote_portField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resource_uriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string roleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string service_tagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string service_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string signalling_nodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string source_aliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string system_locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vendorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bandwidth {
            get {
                return this.bandwidthField;
            }
            set {
                if ((this.bandwidthField.Equals(value) != true)) {
                    this.bandwidthField = value;
                    this.RaisePropertyChanged("bandwidth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string call_direction {
            get {
                return this.call_directionField;
            }
            set {
                if ((object.ReferenceEquals(this.call_directionField, value) != true)) {
                    this.call_directionField = value;
                    this.RaisePropertyChanged("call_direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string call_uuid {
            get {
                return this.call_uuidField;
            }
            set {
                if ((object.ReferenceEquals(this.call_uuidField, value) != true)) {
                    this.call_uuidField = value;
                    this.RaisePropertyChanged("call_uuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string conference {
            get {
                return this.conferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.conferenceField, value) != true)) {
                    this.conferenceField = value;
                    this.RaisePropertyChanged("conference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string connect_time {
            get {
                return this.connect_timeField;
            }
            set {
                if ((object.ReferenceEquals(this.connect_timeField, value) != true)) {
                    this.connect_timeField = value;
                    this.RaisePropertyChanged("connect_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string destination_alias {
            get {
                return this.destination_aliasField;
            }
            set {
                if ((object.ReferenceEquals(this.destination_aliasField, value) != true)) {
                    this.destination_aliasField = value;
                    this.RaisePropertyChanged("destination_alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string display_name {
            get {
                return this.display_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.display_nameField, value) != true)) {
                    this.display_nameField = value;
                    this.RaisePropertyChanged("display_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string encryption {
            get {
                return this.encryptionField;
            }
            set {
                if ((object.ReferenceEquals(this.encryptionField, value) != true)) {
                    this.encryptionField = value;
                    this.RaisePropertyChanged("encryption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool has_media {
            get {
                return this.has_mediaField;
            }
            set {
                if ((this.has_mediaField.Equals(value) != true)) {
                    this.has_mediaField = value;
                    this.RaisePropertyChanged("has_media");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_muted {
            get {
                return this.is_mutedField;
            }
            set {
                if ((this.is_mutedField.Equals(value) != true)) {
                    this.is_mutedField = value;
                    this.RaisePropertyChanged("is_muted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_on_hold {
            get {
                return this.is_on_holdField;
            }
            set {
                if ((this.is_on_holdField.Equals(value) != true)) {
                    this.is_on_holdField = value;
                    this.RaisePropertyChanged("is_on_hold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_presentation_supported {
            get {
                return this.is_presentation_supportedField;
            }
            set {
                if ((this.is_presentation_supportedField.Equals(value) != true)) {
                    this.is_presentation_supportedField = value;
                    this.RaisePropertyChanged("is_presentation_supported");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_presenting {
            get {
                return this.is_presentingField;
            }
            set {
                if ((this.is_presentingField.Equals(value) != true)) {
                    this.is_presentingField = value;
                    this.RaisePropertyChanged("is_presenting");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_streaming {
            get {
                return this.is_streamingField;
            }
            set {
                if ((this.is_streamingField.Equals(value) != true)) {
                    this.is_streamingField = value;
                    this.RaisePropertyChanged("is_streaming");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int license_count {
            get {
                return this.license_countField;
            }
            set {
                if ((this.license_countField.Equals(value) != true)) {
                    this.license_countField = value;
                    this.RaisePropertyChanged("license_count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string media_node {
            get {
                return this.media_nodeField;
            }
            set {
                if ((object.ReferenceEquals(this.media_nodeField, value) != true)) {
                    this.media_nodeField = value;
                    this.RaisePropertyChanged("media_node");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parent_id {
            get {
                return this.parent_idField;
            }
            set {
                if ((object.ReferenceEquals(this.parent_idField, value) != true)) {
                    this.parent_idField = value;
                    this.RaisePropertyChanged("parent_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string participant_alias {
            get {
                return this.participant_aliasField;
            }
            set {
                if ((object.ReferenceEquals(this.participant_aliasField, value) != true)) {
                    this.participant_aliasField = value;
                    this.RaisePropertyChanged("participant_alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string protocol {
            get {
                return this.protocolField;
            }
            set {
                if ((object.ReferenceEquals(this.protocolField, value) != true)) {
                    this.protocolField = value;
                    this.RaisePropertyChanged("protocol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string remote_address {
            get {
                return this.remote_addressField;
            }
            set {
                if ((object.ReferenceEquals(this.remote_addressField, value) != true)) {
                    this.remote_addressField = value;
                    this.RaisePropertyChanged("remote_address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int remote_port {
            get {
                return this.remote_portField;
            }
            set {
                if ((this.remote_portField.Equals(value) != true)) {
                    this.remote_portField = value;
                    this.RaisePropertyChanged("remote_port");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resource_uri {
            get {
                return this.resource_uriField;
            }
            set {
                if ((object.ReferenceEquals(this.resource_uriField, value) != true)) {
                    this.resource_uriField = value;
                    this.RaisePropertyChanged("resource_uri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string role {
            get {
                return this.roleField;
            }
            set {
                if ((object.ReferenceEquals(this.roleField, value) != true)) {
                    this.roleField = value;
                    this.RaisePropertyChanged("role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string service_tag {
            get {
                return this.service_tagField;
            }
            set {
                if ((object.ReferenceEquals(this.service_tagField, value) != true)) {
                    this.service_tagField = value;
                    this.RaisePropertyChanged("service_tag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string service_type {
            get {
                return this.service_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.service_typeField, value) != true)) {
                    this.service_typeField = value;
                    this.RaisePropertyChanged("service_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string signalling_node {
            get {
                return this.signalling_nodeField;
            }
            set {
                if ((object.ReferenceEquals(this.signalling_nodeField, value) != true)) {
                    this.signalling_nodeField = value;
                    this.RaisePropertyChanged("signalling_node");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string source_alias {
            get {
                return this.source_aliasField;
            }
            set {
                if ((object.ReferenceEquals(this.source_aliasField, value) != true)) {
                    this.source_aliasField = value;
                    this.RaisePropertyChanged("source_alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string system_location {
            get {
                return this.system_locationField;
            }
            set {
                if ((object.ReferenceEquals(this.system_locationField, value) != true)) {
                    this.system_locationField = value;
                    this.RaisePropertyChanged("system_location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vendor {
            get {
                return this.vendorField;
            }
            set {
                if ((object.ReferenceEquals(this.vendorField, value) != true)) {
                    this.vendorField = value;
                    this.RaisePropertyChanged("vendor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AllVmrs", Namespace="http://schemas.datacontract.org/2004/07/PepuxService")]
    [System.SerializableAttribute()]
    public partial class AllVmrs : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PepuxFront.IpServiceLink.Aliasess[] aliasesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool allow_guestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PepuxFront.IpServiceLink.AutoPartis[] automatic_participantsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool force_presenter_into_mainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string guest_pinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string guest_viewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string host_viewField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ivr_themeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string max_callrate_inField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string max_callrate_outField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string participant_limitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resource_uriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string service_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sync_tagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PepuxFront.IpServiceLink.Aliasess[] aliases {
            get {
                return this.aliasesField;
            }
            set {
                if ((object.ReferenceEquals(this.aliasesField, value) != true)) {
                    this.aliasesField = value;
                    this.RaisePropertyChanged("aliases");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool allow_guests {
            get {
                return this.allow_guestsField;
            }
            set {
                if ((this.allow_guestsField.Equals(value) != true)) {
                    this.allow_guestsField = value;
                    this.RaisePropertyChanged("allow_guests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PepuxFront.IpServiceLink.AutoPartis[] automatic_participants {
            get {
                return this.automatic_participantsField;
            }
            set {
                if ((object.ReferenceEquals(this.automatic_participantsField, value) != true)) {
                    this.automatic_participantsField = value;
                    this.RaisePropertyChanged("automatic_participants");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool force_presenter_into_main {
            get {
                return this.force_presenter_into_mainField;
            }
            set {
                if ((this.force_presenter_into_mainField.Equals(value) != true)) {
                    this.force_presenter_into_mainField = value;
                    this.RaisePropertyChanged("force_presenter_into_main");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string guest_pin {
            get {
                return this.guest_pinField;
            }
            set {
                if ((object.ReferenceEquals(this.guest_pinField, value) != true)) {
                    this.guest_pinField = value;
                    this.RaisePropertyChanged("guest_pin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string guest_view {
            get {
                return this.guest_viewField;
            }
            set {
                if ((object.ReferenceEquals(this.guest_viewField, value) != true)) {
                    this.guest_viewField = value;
                    this.RaisePropertyChanged("guest_view");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string host_view {
            get {
                return this.host_viewField;
            }
            set {
                if ((object.ReferenceEquals(this.host_viewField, value) != true)) {
                    this.host_viewField = value;
                    this.RaisePropertyChanged("host_view");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ivr_theme {
            get {
                return this.ivr_themeField;
            }
            set {
                if ((object.ReferenceEquals(this.ivr_themeField, value) != true)) {
                    this.ivr_themeField = value;
                    this.RaisePropertyChanged("ivr_theme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string max_callrate_in {
            get {
                return this.max_callrate_inField;
            }
            set {
                if ((object.ReferenceEquals(this.max_callrate_inField, value) != true)) {
                    this.max_callrate_inField = value;
                    this.RaisePropertyChanged("max_callrate_in");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string max_callrate_out {
            get {
                return this.max_callrate_outField;
            }
            set {
                if ((object.ReferenceEquals(this.max_callrate_outField, value) != true)) {
                    this.max_callrate_outField = value;
                    this.RaisePropertyChanged("max_callrate_out");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string participant_limit {
            get {
                return this.participant_limitField;
            }
            set {
                if ((object.ReferenceEquals(this.participant_limitField, value) != true)) {
                    this.participant_limitField = value;
                    this.RaisePropertyChanged("participant_limit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pin {
            get {
                return this.pinField;
            }
            set {
                if ((object.ReferenceEquals(this.pinField, value) != true)) {
                    this.pinField = value;
                    this.RaisePropertyChanged("pin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resource_uri {
            get {
                return this.resource_uriField;
            }
            set {
                if ((object.ReferenceEquals(this.resource_uriField, value) != true)) {
                    this.resource_uriField = value;
                    this.RaisePropertyChanged("resource_uri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string service_type {
            get {
                return this.service_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.service_typeField, value) != true)) {
                    this.service_typeField = value;
                    this.RaisePropertyChanged("service_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sync_tag {
            get {
                return this.sync_tagField;
            }
            set {
                if ((object.ReferenceEquals(this.sync_tagField, value) != true)) {
                    this.sync_tagField = value;
                    this.RaisePropertyChanged("sync_tag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tag {
            get {
                return this.tagField;
            }
            set {
                if ((object.ReferenceEquals(this.tagField, value) != true)) {
                    this.tagField = value;
                    this.RaisePropertyChanged("tag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Aliasess", Namespace="http://schemas.datacontract.org/2004/07/PepuxService")]
    [System.SerializableAttribute()]
    public partial class Aliasess : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string conferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alias {
            get {
                return this.aliasField;
            }
            set {
                if ((object.ReferenceEquals(this.aliasField, value) != true)) {
                    this.aliasField = value;
                    this.RaisePropertyChanged("alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string conference {
            get {
                return this.conferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.conferenceField, value) != true)) {
                    this.conferenceField = value;
                    this.RaisePropertyChanged("conference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutoPartis", Namespace="http://schemas.datacontract.org/2004/07/PepuxService")]
    [System.SerializableAttribute()]
    public partial class AutoPartis : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string aliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dtmf_sequenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string protocolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string roleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool streamingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string alias {
            get {
                return this.aliasField;
            }
            set {
                if ((object.ReferenceEquals(this.aliasField, value) != true)) {
                    this.aliasField = value;
                    this.RaisePropertyChanged("alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dtmf_sequence {
            get {
                return this.dtmf_sequenceField;
            }
            set {
                if ((object.ReferenceEquals(this.dtmf_sequenceField, value) != true)) {
                    this.dtmf_sequenceField = value;
                    this.RaisePropertyChanged("dtmf_sequence");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string protocol {
            get {
                return this.protocolField;
            }
            set {
                if ((object.ReferenceEquals(this.protocolField, value) != true)) {
                    this.protocolField = value;
                    this.RaisePropertyChanged("protocol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string role {
            get {
                return this.roleField;
            }
            set {
                if ((object.ReferenceEquals(this.roleField, value) != true)) {
                    this.roleField = value;
                    this.RaisePropertyChanged("role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool streaming {
            get {
                return this.streamingField;
            }
            set {
                if ((this.streamingField.Equals(value) != true)) {
                    this.streamingField = value;
                    this.RaisePropertyChanged("streaming");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="allrecords", Namespace="http://schemas.datacontract.org/2004/07/PepuxService")]
    [System.SerializableAttribute()]
    public partial class allrecords : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConfField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TstartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TfinishField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Conf {
            get {
                return this.ConfField;
            }
            set {
                if ((object.ReferenceEquals(this.ConfField, value) != true)) {
                    this.ConfField = value;
                    this.RaisePropertyChanged("Conf");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string PName {
            get {
                return this.PNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PNameField, value) != true)) {
                    this.PNameField = value;
                    this.RaisePropertyChanged("PName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime Tstart {
            get {
                return this.TstartField;
            }
            set {
                if ((this.TstartField.Equals(value) != true)) {
                    this.TstartField = value;
                    this.RaisePropertyChanged("Tstart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.DateTime Tfinish {
            get {
                return this.TfinishField;
            }
            set {
                if ((this.TfinishField.Equals(value) != true)) {
                    this.TfinishField = value;
                    this.RaisePropertyChanged("Tfinish");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Link {
            get {
                return this.LinkField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkField, value) != true)) {
                    this.LinkField = value;
                    this.RaisePropertyChanged("Link");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="pbrec", Namespace="http://schemas.datacontract.org/2004/07/PepuxService")]
    [System.SerializableAttribute()]
    public partial class pbrec : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="addrec", Namespace="http://schemas.datacontract.org/2004/07/PepuxService")]
    [System.SerializableAttribute()]
    public partial class addrec : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string h323_addField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string positionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sip_addField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string surnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tel_extField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tel_intField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tel_mobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string timezoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string h323_add {
            get {
                return this.h323_addField;
            }
            set {
                if ((object.ReferenceEquals(this.h323_addField, value) != true)) {
                    this.h323_addField = value;
                    this.RaisePropertyChanged("h323_add");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string position {
            get {
                return this.positionField;
            }
            set {
                if ((object.ReferenceEquals(this.positionField, value) != true)) {
                    this.positionField = value;
                    this.RaisePropertyChanged("position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sip_add {
            get {
                return this.sip_addField;
            }
            set {
                if ((object.ReferenceEquals(this.sip_addField, value) != true)) {
                    this.sip_addField = value;
                    this.RaisePropertyChanged("sip_add");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                if ((object.ReferenceEquals(this.surnameField, value) != true)) {
                    this.surnameField = value;
                    this.RaisePropertyChanged("surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tel_ext {
            get {
                return this.tel_extField;
            }
            set {
                if ((object.ReferenceEquals(this.tel_extField, value) != true)) {
                    this.tel_extField = value;
                    this.RaisePropertyChanged("tel_ext");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tel_int {
            get {
                return this.tel_intField;
            }
            set {
                if ((object.ReferenceEquals(this.tel_intField, value) != true)) {
                    this.tel_intField = value;
                    this.RaisePropertyChanged("tel_int");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tel_mob {
            get {
                return this.tel_mobField;
            }
            set {
                if ((object.ReferenceEquals(this.tel_mobField, value) != true)) {
                    this.tel_mobField = value;
                    this.RaisePropertyChanged("tel_mob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string timezone {
            get {
                return this.timezoneField;
            }
            set {
                if ((object.ReferenceEquals(this.timezoneField, value) != true)) {
                    this.timezoneField = value;
                    this.RaisePropertyChanged("timezone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IpServiceLink.IPService")]
    public interface IPService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/GetActiveConfs", ReplyAction="http://tempuri.org/IPService/GetActiveConfsResponse")]
        PepuxFront.IpServiceLink.ActiveConfs[] GetActiveConfs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/GetActiveConfs", ReplyAction="http://tempuri.org/IPService/GetActiveConfsResponse")]
        System.Threading.Tasks.Task<PepuxFront.IpServiceLink.ActiveConfs[]> GetActiveConfsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/GetDataLocal", ReplyAction="http://tempuri.org/IPService/GetDataLocalResponse")]
        PepuxFront.IpServiceLink.Service[] GetDataLocal();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/GetDataLocal", ReplyAction="http://tempuri.org/IPService/GetDataLocalResponse")]
        System.Threading.Tasks.Task<PepuxFront.IpServiceLink.Service[]> GetDataLocalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/GetActiveParts", ReplyAction="http://tempuri.org/IPService/GetActivePartsResponse")]
        PepuxFront.IpServiceLink.participants[] GetActiveParts(string confname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/GetActiveParts", ReplyAction="http://tempuri.org/IPService/GetActivePartsResponse")]
        System.Threading.Tasks.Task<PepuxFront.IpServiceLink.participants[]> GetActivePartsAsync(string confname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/GetVmrList", ReplyAction="http://tempuri.org/IPService/GetVmrListResponse")]
        PepuxFront.IpServiceLink.AllVmrs[] GetVmrList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/GetVmrList", ReplyAction="http://tempuri.org/IPService/GetVmrListResponse")]
        System.Threading.Tasks.Task<PepuxFront.IpServiceLink.AllVmrs[]> GetVmrListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/GetToken", ReplyAction="http://tempuri.org/IPService/GetTokenResponse")]
        string GetToken(string confname, string dispname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/GetToken", ReplyAction="http://tempuri.org/IPService/GetTokenResponse")]
        System.Threading.Tasks.Task<string> GetTokenAsync(string confname, string dispname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/Token_refresh", ReplyAction="http://tempuri.org/IPService/Token_refreshResponse")]
        string Token_refresh(string confname, string old_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/Token_refresh", ReplyAction="http://tempuri.org/IPService/Token_refreshResponse")]
        System.Threading.Tasks.Task<string> Token_refreshAsync(string confname, string old_token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/Videorecords", ReplyAction="http://tempuri.org/IPService/VideorecordsResponse")]
        PepuxFront.IpServiceLink.allrecords[] Videorecords(string val);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/Videorecords", ReplyAction="http://tempuri.org/IPService/VideorecordsResponse")]
        System.Threading.Tasks.Task<PepuxFront.IpServiceLink.allrecords[]> VideorecordsAsync(string val);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/GetPhonebookUsers", ReplyAction="http://tempuri.org/IPService/GetPhonebookUsersResponse")]
        PepuxFront.IpServiceLink.pbrec[] GetPhonebookUsers(string Uname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/GetPhonebookUsers", ReplyAction="http://tempuri.org/IPService/GetPhonebookUsersResponse")]
        System.Threading.Tasks.Task<PepuxFront.IpServiceLink.pbrec[]> GetPhonebookUsersAsync(string Uname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/AddRecordsToPB", ReplyAction="http://tempuri.org/IPService/AddRecordsToPBResponse")]
        PepuxFront.IpServiceLink.addrec AddRecordsToPB(string in_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/AddRecordsToPB", ReplyAction="http://tempuri.org/IPService/AddRecordsToPBResponse")]
        System.Threading.Tasks.Task<PepuxFront.IpServiceLink.addrec> AddRecordsToPBAsync(string in_name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/Authenticate", ReplyAction="http://tempuri.org/IPService/AuthenticateResponse")]
        bool Authenticate(string userName, string password, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/Authenticate", ReplyAction="http://tempuri.org/IPService/AuthenticateResponse")]
        System.Threading.Tasks.Task<bool> AuthenticateAsync(string userName, string password, string domain);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/Groups", ReplyAction="http://tempuri.org/IPService/GroupsResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PepuxFront.IpServiceLink.ActiveConfs[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PepuxFront.IpServiceLink.ActiveConfs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PepuxFront.IpServiceLink.Service[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PepuxFront.IpServiceLink.Service))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PepuxFront.IpServiceLink.Phonebook[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PepuxFront.IpServiceLink.Phonebook))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PepuxFront.IpServiceLink.participants[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PepuxFront.IpServiceLink.participants))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PepuxFront.IpServiceLink.AllVmrs[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PepuxFront.IpServiceLink.AllVmrs))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PepuxFront.IpServiceLink.Aliasess[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PepuxFront.IpServiceLink.Aliasess))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PepuxFront.IpServiceLink.AutoPartis[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PepuxFront.IpServiceLink.AutoPartis))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PepuxFront.IpServiceLink.allrecords[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PepuxFront.IpServiceLink.allrecords))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PepuxFront.IpServiceLink.pbrec[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PepuxFront.IpServiceLink.pbrec))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(PepuxFront.IpServiceLink.addrec))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        object[] Groups();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/Groups", ReplyAction="http://tempuri.org/IPService/GroupsResponse")]
        System.Threading.Tasks.Task<object[]> GroupsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPServiceChannel : PepuxFront.IpServiceLink.IPService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PServiceClient : System.ServiceModel.ClientBase<PepuxFront.IpServiceLink.IPService>, PepuxFront.IpServiceLink.IPService {
        
        public PServiceClient() {
        }
        
        public PServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PepuxFront.IpServiceLink.ActiveConfs[] GetActiveConfs() {
            return base.Channel.GetActiveConfs();
        }
        
        public System.Threading.Tasks.Task<PepuxFront.IpServiceLink.ActiveConfs[]> GetActiveConfsAsync() {
            return base.Channel.GetActiveConfsAsync();
        }
        
        public PepuxFront.IpServiceLink.Service[] GetDataLocal() {
            return base.Channel.GetDataLocal();
        }
        
        public System.Threading.Tasks.Task<PepuxFront.IpServiceLink.Service[]> GetDataLocalAsync() {
            return base.Channel.GetDataLocalAsync();
        }
        
        public PepuxFront.IpServiceLink.participants[] GetActiveParts(string confname) {
            return base.Channel.GetActiveParts(confname);
        }
        
        public System.Threading.Tasks.Task<PepuxFront.IpServiceLink.participants[]> GetActivePartsAsync(string confname) {
            return base.Channel.GetActivePartsAsync(confname);
        }
        
        public PepuxFront.IpServiceLink.AllVmrs[] GetVmrList() {
            return base.Channel.GetVmrList();
        }
        
        public System.Threading.Tasks.Task<PepuxFront.IpServiceLink.AllVmrs[]> GetVmrListAsync() {
            return base.Channel.GetVmrListAsync();
        }
        
        public string GetToken(string confname, string dispname) {
            return base.Channel.GetToken(confname, dispname);
        }
        
        public System.Threading.Tasks.Task<string> GetTokenAsync(string confname, string dispname) {
            return base.Channel.GetTokenAsync(confname, dispname);
        }
        
        public string Token_refresh(string confname, string old_token) {
            return base.Channel.Token_refresh(confname, old_token);
        }
        
        public System.Threading.Tasks.Task<string> Token_refreshAsync(string confname, string old_token) {
            return base.Channel.Token_refreshAsync(confname, old_token);
        }
        
        public PepuxFront.IpServiceLink.allrecords[] Videorecords(string val) {
            return base.Channel.Videorecords(val);
        }
        
        public System.Threading.Tasks.Task<PepuxFront.IpServiceLink.allrecords[]> VideorecordsAsync(string val) {
            return base.Channel.VideorecordsAsync(val);
        }
        
        public PepuxFront.IpServiceLink.pbrec[] GetPhonebookUsers(string Uname) {
            return base.Channel.GetPhonebookUsers(Uname);
        }
        
        public System.Threading.Tasks.Task<PepuxFront.IpServiceLink.pbrec[]> GetPhonebookUsersAsync(string Uname) {
            return base.Channel.GetPhonebookUsersAsync(Uname);
        }
        
        public PepuxFront.IpServiceLink.addrec AddRecordsToPB(string in_name) {
            return base.Channel.AddRecordsToPB(in_name);
        }
        
        public System.Threading.Tasks.Task<PepuxFront.IpServiceLink.addrec> AddRecordsToPBAsync(string in_name) {
            return base.Channel.AddRecordsToPBAsync(in_name);
        }
        
        public bool Authenticate(string userName, string password, string domain) {
            return base.Channel.Authenticate(userName, password, domain);
        }
        
        public System.Threading.Tasks.Task<bool> AuthenticateAsync(string userName, string password, string domain) {
            return base.Channel.AuthenticateAsync(userName, password, domain);
        }
        
        public object[] Groups() {
            return base.Channel.Groups();
        }
        
        public System.Threading.Tasks.Task<object[]> GroupsAsync() {
            return base.Channel.GroupsAsync();
        }
    }
}
