//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PepuxFront.IpServiceLink {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="objects", Namespace="http://schemas.datacontract.org/2004/07/PepuxService")]
    [System.SerializableAttribute()]
    public partial class objects : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_lockedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lock_pathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resource_uriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string service_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string start_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string start_time2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_locked {
            get {
                return this.is_lockedField;
            }
            set {
                if ((this.is_lockedField.Equals(value) != true)) {
                    this.is_lockedField = value;
                    this.RaisePropertyChanged("is_locked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lock_path {
            get {
                return this.lock_pathField;
            }
            set {
                if ((object.ReferenceEquals(this.lock_pathField, value) != true)) {
                    this.lock_pathField = value;
                    this.RaisePropertyChanged("lock_path");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resource_uri {
            get {
                return this.resource_uriField;
            }
            set {
                if ((object.ReferenceEquals(this.resource_uriField, value) != true)) {
                    this.resource_uriField = value;
                    this.RaisePropertyChanged("resource_uri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string service_type {
            get {
                return this.service_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.service_typeField, value) != true)) {
                    this.service_typeField = value;
                    this.RaisePropertyChanged("service_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string start_time {
            get {
                return this.start_timeField;
            }
            set {
                if ((object.ReferenceEquals(this.start_timeField, value) != true)) {
                    this.start_timeField = value;
                    this.RaisePropertyChanged("start_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string start_time2 {
            get {
                return this.start_time2Field;
            }
            set {
                if ((object.ReferenceEquals(this.start_time2Field, value) != true)) {
                    this.start_time2Field = value;
                    this.RaisePropertyChanged("start_time2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tag {
            get {
                return this.tagField;
            }
            set {
                if ((object.ReferenceEquals(this.tagField, value) != true)) {
                    this.tagField = value;
                    this.RaisePropertyChanged("tag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Service", Namespace="http://schemas.datacontract.org/2004/07/PepuxService")]
    [System.SerializableAttribute()]
    public partial class Service : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdName {
            get {
                return this.AdNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AdNameField, value) != true)) {
                    this.AdNameField = value;
                    this.RaisePropertyChanged("AdName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="participantsAll", Namespace="http://schemas.datacontract.org/2004/07/PepuxService")]
    [System.SerializableAttribute()]
    public partial class participantsAll : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int bandwidthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string call_directionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string call_uuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string conferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string connect_timeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string destination_aliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string display_nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string encryptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool has_mediaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_mutedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_on_holdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_presentation_supportedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_presentingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_streamingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int license_countField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string media_nodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parent_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string participant_aliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string protocolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string remote_addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int remote_portField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resource_uriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string roleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string service_tagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string service_typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string signalling_nodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string source_aliasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string system_locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string vendorField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bandwidth {
            get {
                return this.bandwidthField;
            }
            set {
                if ((this.bandwidthField.Equals(value) != true)) {
                    this.bandwidthField = value;
                    this.RaisePropertyChanged("bandwidth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string call_direction {
            get {
                return this.call_directionField;
            }
            set {
                if ((object.ReferenceEquals(this.call_directionField, value) != true)) {
                    this.call_directionField = value;
                    this.RaisePropertyChanged("call_direction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string call_uuid {
            get {
                return this.call_uuidField;
            }
            set {
                if ((object.ReferenceEquals(this.call_uuidField, value) != true)) {
                    this.call_uuidField = value;
                    this.RaisePropertyChanged("call_uuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string conference {
            get {
                return this.conferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.conferenceField, value) != true)) {
                    this.conferenceField = value;
                    this.RaisePropertyChanged("conference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string connect_time {
            get {
                return this.connect_timeField;
            }
            set {
                if ((object.ReferenceEquals(this.connect_timeField, value) != true)) {
                    this.connect_timeField = value;
                    this.RaisePropertyChanged("connect_time");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string destination_alias {
            get {
                return this.destination_aliasField;
            }
            set {
                if ((object.ReferenceEquals(this.destination_aliasField, value) != true)) {
                    this.destination_aliasField = value;
                    this.RaisePropertyChanged("destination_alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string display_name {
            get {
                return this.display_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.display_nameField, value) != true)) {
                    this.display_nameField = value;
                    this.RaisePropertyChanged("display_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string encryption {
            get {
                return this.encryptionField;
            }
            set {
                if ((object.ReferenceEquals(this.encryptionField, value) != true)) {
                    this.encryptionField = value;
                    this.RaisePropertyChanged("encryption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool has_media {
            get {
                return this.has_mediaField;
            }
            set {
                if ((this.has_mediaField.Equals(value) != true)) {
                    this.has_mediaField = value;
                    this.RaisePropertyChanged("has_media");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_muted {
            get {
                return this.is_mutedField;
            }
            set {
                if ((this.is_mutedField.Equals(value) != true)) {
                    this.is_mutedField = value;
                    this.RaisePropertyChanged("is_muted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_on_hold {
            get {
                return this.is_on_holdField;
            }
            set {
                if ((this.is_on_holdField.Equals(value) != true)) {
                    this.is_on_holdField = value;
                    this.RaisePropertyChanged("is_on_hold");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_presentation_supported {
            get {
                return this.is_presentation_supportedField;
            }
            set {
                if ((this.is_presentation_supportedField.Equals(value) != true)) {
                    this.is_presentation_supportedField = value;
                    this.RaisePropertyChanged("is_presentation_supported");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_presenting {
            get {
                return this.is_presentingField;
            }
            set {
                if ((this.is_presentingField.Equals(value) != true)) {
                    this.is_presentingField = value;
                    this.RaisePropertyChanged("is_presenting");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_streaming {
            get {
                return this.is_streamingField;
            }
            set {
                if ((this.is_streamingField.Equals(value) != true)) {
                    this.is_streamingField = value;
                    this.RaisePropertyChanged("is_streaming");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int license_count {
            get {
                return this.license_countField;
            }
            set {
                if ((this.license_countField.Equals(value) != true)) {
                    this.license_countField = value;
                    this.RaisePropertyChanged("license_count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string media_node {
            get {
                return this.media_nodeField;
            }
            set {
                if ((object.ReferenceEquals(this.media_nodeField, value) != true)) {
                    this.media_nodeField = value;
                    this.RaisePropertyChanged("media_node");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parent_id {
            get {
                return this.parent_idField;
            }
            set {
                if ((object.ReferenceEquals(this.parent_idField, value) != true)) {
                    this.parent_idField = value;
                    this.RaisePropertyChanged("parent_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string participant_alias {
            get {
                return this.participant_aliasField;
            }
            set {
                if ((object.ReferenceEquals(this.participant_aliasField, value) != true)) {
                    this.participant_aliasField = value;
                    this.RaisePropertyChanged("participant_alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string protocol {
            get {
                return this.protocolField;
            }
            set {
                if ((object.ReferenceEquals(this.protocolField, value) != true)) {
                    this.protocolField = value;
                    this.RaisePropertyChanged("protocol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string remote_address {
            get {
                return this.remote_addressField;
            }
            set {
                if ((object.ReferenceEquals(this.remote_addressField, value) != true)) {
                    this.remote_addressField = value;
                    this.RaisePropertyChanged("remote_address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int remote_port {
            get {
                return this.remote_portField;
            }
            set {
                if ((this.remote_portField.Equals(value) != true)) {
                    this.remote_portField = value;
                    this.RaisePropertyChanged("remote_port");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string resource_uri {
            get {
                return this.resource_uriField;
            }
            set {
                if ((object.ReferenceEquals(this.resource_uriField, value) != true)) {
                    this.resource_uriField = value;
                    this.RaisePropertyChanged("resource_uri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string role {
            get {
                return this.roleField;
            }
            set {
                if ((object.ReferenceEquals(this.roleField, value) != true)) {
                    this.roleField = value;
                    this.RaisePropertyChanged("role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string service_tag {
            get {
                return this.service_tagField;
            }
            set {
                if ((object.ReferenceEquals(this.service_tagField, value) != true)) {
                    this.service_tagField = value;
                    this.RaisePropertyChanged("service_tag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string service_type {
            get {
                return this.service_typeField;
            }
            set {
                if ((object.ReferenceEquals(this.service_typeField, value) != true)) {
                    this.service_typeField = value;
                    this.RaisePropertyChanged("service_type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string signalling_node {
            get {
                return this.signalling_nodeField;
            }
            set {
                if ((object.ReferenceEquals(this.signalling_nodeField, value) != true)) {
                    this.signalling_nodeField = value;
                    this.RaisePropertyChanged("signalling_node");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string source_alias {
            get {
                return this.source_aliasField;
            }
            set {
                if ((object.ReferenceEquals(this.source_aliasField, value) != true)) {
                    this.source_aliasField = value;
                    this.RaisePropertyChanged("source_alias");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string system_location {
            get {
                return this.system_locationField;
            }
            set {
                if ((object.ReferenceEquals(this.system_locationField, value) != true)) {
                    this.system_locationField = value;
                    this.RaisePropertyChanged("system_location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string vendor {
            get {
                return this.vendorField;
            }
            set {
                if ((object.ReferenceEquals(this.vendorField, value) != true)) {
                    this.vendorField = value;
                    this.RaisePropertyChanged("vendor");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IpServiceLink.IPService")]
    public interface IPService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/GetActiveConfs", ReplyAction="http://tempuri.org/IPService/GetActiveConfsResponse")]
        PepuxFront.IpServiceLink.objects[] GetActiveConfs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/GetActiveConfs", ReplyAction="http://tempuri.org/IPService/GetActiveConfsResponse")]
        System.Threading.Tasks.Task<PepuxFront.IpServiceLink.objects[]> GetActiveConfsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/GetDataLocal", ReplyAction="http://tempuri.org/IPService/GetDataLocalResponse")]
        PepuxFront.IpServiceLink.Service[] GetDataLocal();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/GetDataLocal", ReplyAction="http://tempuri.org/IPService/GetDataLocalResponse")]
        System.Threading.Tasks.Task<PepuxFront.IpServiceLink.Service[]> GetDataLocalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/GetActiveParts", ReplyAction="http://tempuri.org/IPService/GetActivePartsResponse")]
        PepuxFront.IpServiceLink.participantsAll[] GetActiveParts(string confname);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPService/GetActiveParts", ReplyAction="http://tempuri.org/IPService/GetActivePartsResponse")]
        System.Threading.Tasks.Task<PepuxFront.IpServiceLink.participantsAll[]> GetActivePartsAsync(string confname);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPServiceChannel : PepuxFront.IpServiceLink.IPService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PServiceClient : System.ServiceModel.ClientBase<PepuxFront.IpServiceLink.IPService>, PepuxFront.IpServiceLink.IPService {
        
        public PServiceClient() {
        }
        
        public PServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PepuxFront.IpServiceLink.objects[] GetActiveConfs() {
            return base.Channel.GetActiveConfs();
        }
        
        public System.Threading.Tasks.Task<PepuxFront.IpServiceLink.objects[]> GetActiveConfsAsync() {
            return base.Channel.GetActiveConfsAsync();
        }
        
        public PepuxFront.IpServiceLink.Service[] GetDataLocal() {
            return base.Channel.GetDataLocal();
        }
        
        public System.Threading.Tasks.Task<PepuxFront.IpServiceLink.Service[]> GetDataLocalAsync() {
            return base.Channel.GetDataLocalAsync();
        }
        
        public PepuxFront.IpServiceLink.participantsAll[] GetActiveParts(string confname) {
            return base.Channel.GetActiveParts(confname);
        }
        
        public System.Threading.Tasks.Task<PepuxFront.IpServiceLink.participantsAll[]> GetActivePartsAsync(string confname) {
            return base.Channel.GetActivePartsAsync(confname);
        }
    }
}
